import {Images,Sparkles} from "lucide-react";
import {mediaRepository} from "@/repositories/media.repository";
import {GalleryEmpty,ImageGallery} from "@/components/public/image-gallery";
import {Pagination} from "@/components/ui";
import {ListingFilters} from "@/components/public/listing-filters";
import {CharacterFilter} from "@/components/public/character-filter";
import {hasClubAccess} from "@/lib/club-access";
export const metadata={title:"Galerie d’illustrations pour enfants",description:"Découvrez les créations originales du Petit Crayon.",alternates:{canonical:"/images"}};
export default async function ImagesPage({searchParams}:{searchParams:Promise<{page?:string;q?:string;category?:string;character?:string;sort?:string}>}){
 const params=await searchParams,sort=params.sort==="oldest"?"oldest":"newest",clubAccess=await hasClubAccess();
 const[result,categories,characters]=await Promise.all([mediaRepository.paginatedImages({page:Number(params.page)||1,pageSize:12,search:params.q,category:params.category,character:params.character,sort,includeClub:clubAccess,language:"FR"}),mediaRepository.imageCategoryOptions("FR"),mediaRepository.characterOptions("FR")]),filtered=Boolean(params.q?.trim()||params.category||params.character);
 return <section className="min-h-[calc(100vh-4rem)] bg-gradient-to-b from-[#f7f4ed] to-background py-6 dark:from-[#111a18] dark:to-background md:py-8"><div className="container"><header className="mb-5 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><span className="inline-flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-primary"><Sparkles size={14}/>Galerie créative</span><h1 className="mt-2 font-display text-3xl font-black dark:text-white md:text-4xl">Un monde à découvrir <span className="text-primary">en images.</span></h1><p className="mt-1.5 text-sm text-foreground/65 md:text-base">Des créations originales à explorer, aimer et retrouver en famille.</p></div><div className="inline-flex w-fit items-center gap-2 rounded-2xl border bg-card/85 px-3 py-2"><Images className="text-primary" size={18}/><strong>{result.total}</strong><span className="text-xs text-foreground/55">image{result.total>1?"s":""}</span></div></header><ListingFilters title="Trouver une illustration" query={params.q} category={params.category} sort={sort} categories={categories} searchPlaceholder="Titre, personnage, catégorie…"/><CharacterFilter options={characters} selected={params.character} path="/images" query={{q:params.q,category:params.category,sort}}/><p className="mb-4 text-sm font-semibold text-foreground/60">{result.total} image{result.total>1?"s":""} trouvée{result.total>1?"s":""}</p>{result.items.length?<ImageGallery items={result.items}/>:<GalleryEmpty filtered={filtered} resetHref="/images"/>}<Pagination page={result.page} pages={result.pages} path="/images" query={{q:params.q,category:params.category,character:params.character,sort}}/></div></section>;
}
