import { Images, Sparkles } from "lucide-react";
import { mediaRepository } from "@/repositories/media.repository";
import { GalleryEmpty, ImageGallery } from "@/components/public/image-gallery";
import { Pagination } from "@/components/ui";
import { ListingFilters } from "@/components/public/listing-filters";

export const metadata = { title: "Galerie d’illustrations pour enfants", description: "Découvrez les illustrations colorées, couvertures et créations originales du Petit Crayon.", alternates: { canonical: "/images" }, openGraph: { url: "/images", title: "Galerie créative du Petit Crayon", description: "Un univers d’illustrations joyeuses imaginées pour les enfants." } };
export default async function ImagesPage({ searchParams }: { searchParams: Promise<{ page?: string;q?:string;category?:string;sort?:string }> }) {
  const params = await searchParams;
  const sort=params.sort==="oldest"?"oldest":"newest";
  const [result,categories] = await Promise.all([mediaRepository.paginatedImages({page:Number(params.page)||1,pageSize:12,search:params.q,category:params.category,sort}),mediaRepository.imageCategoryOptions()]);
  return <section className="relative min-h-[calc(100vh-4rem)] overflow-hidden bg-gradient-to-b from-[#f7f4ed] to-background py-6 dark:from-[#111a18] dark:via-[#121a19] dark:to-background md:py-8"><div className="pointer-events-none absolute -left-20 -top-20 size-64 rounded-full bg-emerald-200/25 blur-3xl dark:bg-emerald-500/10"/><div className="pointer-events-none absolute -right-20 top-0 size-72 rounded-full bg-orange-200/25 blur-3xl dark:bg-orange-400/10"/><div className="container relative"><header className="mb-5 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><span className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[.18em] text-primary md:text-xs"><Sparkles size={14}/> Galerie créative</span><h1 className="mt-2 font-display text-3xl font-black leading-tight text-slate-900 dark:text-white md:text-4xl">Un monde à découvrir <span className="text-primary">en images.</span></h1><p className="mt-1.5 text-sm text-slate-600 dark:text-slate-300 md:text-base">Illustrations, couvertures et petits instants créatifs imaginés pour faire sourire les enfants.</p></div><div className="inline-flex w-fit items-center gap-2.5 rounded-2xl border bg-card/85 px-3 py-2 shadow-sm dark:border-white/10 dark:bg-white/5"><Images className="text-primary" size={18}/><strong className="text-lg leading-none">{result.total}</strong><span className="text-xs font-semibold text-foreground/55">image{result.total>1?'s':''}</span></div></header><ListingFilters title="Trouver une illustration" query={params.q} category={params.category} sort={sort} categories={categories} searchPlaceholder="Rechercher une image…"/><p className="mb-4 text-sm font-semibold text-foreground/60">{result.total} image{result.total>1?"s":""} trouvée{result.total>1?"s":""}</p>{result.items.length?<ImageGallery items={result.items}/>:<GalleryEmpty/>}<Pagination page={result.page} pages={result.pages} path="/images" query={{q:params.q,category:params.category,sort}}/></div></section>;
}
