import type { Metadata } from "next";
import { contentRepository } from "@/repositories/content.repository";
import { BookCard } from "@/components/content-cards";
import { BookFilters } from "@/components/public/book-filters";
import { EmptyState, Pagination } from "@/components/ui";

export const metadata: Metadata = { title: "Livres de coloriage et d’activités pour enfants", description: "Découvrez nos livres de coloriage, jeux éducatifs et cahiers d’activités adaptés aux enfants de 3 à 8 ans.", alternates: { canonical: "/livres" }, openGraph: { url: "/livres", title: "Livres créatifs pour enfants | Le Petit Crayon", description: "Coloriages, jeux éducatifs et aventures créatives pour apprendre en s’amusant." } };
type Params={page?:string;q?:string;category?:string;pricing?:string;sort?:string};
export default async function Page({searchParams}:{searchParams:Promise<Params>}){const s=await searchParams,pricing=s.pricing==="FREE"||s.pricing==="PAID"?s.pricing:undefined,sort=s.sort==="oldest"?"oldest":"newest",[r,categories]=await Promise.all([contentRepository.books({page:Number(s.page)||1,search:s.q,category:s.category,pricing,sort,pageSize:12}),contentRepository.bookCategories()]);return <div className="container py-6 md:py-8"><header className="mb-5"><p className="text-xs font-black uppercase tracking-[.2em] text-primary md:text-sm">La bibliothèque</p><div className="mt-2 flex flex-col gap-2 lg:flex-row lg:items-end lg:justify-between lg:gap-8"><h1 className="text-balance font-display text-3xl font-black leading-[1.05] tracking-tight md:text-4xl lg:whitespace-nowrap">Des livres pour nourrir l’imaginaire</h1><p className="shrink-0 text-sm font-semibold text-foreground/60 md:text-base">Coloriage, jeux et aventures adaptés à chaque âge.</p></div></header><BookFilters query={s.q} category={s.category} pricing={pricing} sort={sort} categories={categories}/><p className="mb-4 text-sm font-semibold text-foreground/60">{r.total} livre{r.total>1?"s":""} trouvé{r.total>1?"s":""}</p><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{r.items.length?r.items.map((x,i)=><BookCard key={x.book.id} item={x.book} coverPath={x.cover?.path} gallery={x.gallery} index={i}/>):<EmptyState title="Aucun livre trouvé"/>}</div><Pagination page={r.page} pages={r.pages} path="/livres" query={{q:s.q,category:s.category,pricing,sort}}/></div>}
