import sharp from "sharp";

type PdfImage={data:Buffer;width:number;height:number};
export async function imagesToPdf(files:File[]){const images:PdfImage[]=[];for(const file of files){const pipeline=sharp(Buffer.from(await file.arrayBuffer())).rotate().flatten({background:"#ffffff"}).jpeg({quality:92,mozjpeg:true});const {data,info}=await pipeline.toBuffer({resolveWithObject:true});images.push({data,width:info.width,height:info.height})}return buildPdf(images)}

export async function imagesWithModelsToPdf(entries:Array<{page:Buffer;model:Buffer|null}>){
  const composed:PdfImage[]=[];
  for(const entry of entries){
    const canvasWidth=1240,canvasHeight=1754,margin=36;
    const page=await sharp(entry.page).rotate().flatten({background:"#ffffff"}).resize({width:canvasWidth-margin*2,height:canvasHeight-margin*2,fit:"inside",withoutEnlargement:false}).png().toBuffer({resolveWithObject:true});
    const layers:Array<{input:Buffer;left:number;top:number}>=[{input:page.data,left:Math.round((canvasWidth-page.info.width)/2),top:Math.round((canvasHeight-page.info.height)/2)}];
    if(entry.model){const model=await sharp(entry.model).rotate().flatten({background:"#ffffff"}).resize({width:Math.round(canvasWidth*.23),height:Math.round(canvasHeight*.23),fit:"inside",withoutEnlargement:false}).extend({top:8,bottom:8,left:8,right:8,background:"#ffffff"}).jpeg({quality:94,mozjpeg:true}).toBuffer({resolveWithObject:true});layers.push({input:model.data,left:canvasWidth-model.info.width,top:0})}
    const rendered=await sharp({create:{width:canvasWidth,height:canvasHeight,channels:3,background:"#ffffff"}}).composite(layers).jpeg({quality:92,mozjpeg:true}).toBuffer({resolveWithObject:true});
    composed.push({data:rendered.data,width:rendered.info.width,height:rendered.info.height});
  }
  return buildPdf(composed);
}

function buildPdf(images:PdfImage[]){const objects:Buffer[]=[];const add=(value:string|Buffer)=>objects.push(Buffer.isBuffer(value)?value:Buffer.from(value,"binary"));const pageIds=images.map((_,index)=>3+index*3);add("<< /Type /Catalog /Pages 2 0 R >>");add(`<< /Type /Pages /Kids [${pageIds.map(id=>`${id} 0 R`).join(" ")}] /Count ${images.length} >>`);images.forEach((image,index)=>{const pageId=3+index*3,imageId=pageId+1,contentId=pageId+2,pageWidth=595.28,pageHeight=841.89,margin=28,maxWidth=pageWidth-margin*2,maxHeight=pageHeight-margin*2,scale=Math.min(maxWidth/image.width,maxHeight/image.height),width=image.width*scale,height=image.height*scale,x=(pageWidth-width)/2,y=(pageHeight-height)/2,commands=`q\n${width.toFixed(2)} 0 0 ${height.toFixed(2)} ${x.toFixed(2)} ${y.toFixed(2)} cm\n/Im${index} Do\nQ\n`;add(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /XObject << /Im${index} ${imageId} 0 R >> >> /Contents ${contentId} 0 R >>`);add(Buffer.concat([Buffer.from(`<< /Type /XObject /Subtype /Image /Width ${image.width} /Height ${image.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${image.data.length} >>\nstream\n`,"binary"),image.data,Buffer.from("\nendstream","binary")]));add(`<< /Length ${Buffer.byteLength(commands)} >>\nstream\n${commands}endstream`) });const header=Buffer.from("%PDF-1.4\n%\xE2\xE3\xCF\xD3\n","binary"),parts=[header],offsets=[0];let offset=header.length;objects.forEach((object,index)=>{offsets.push(offset);const wrapped=Buffer.concat([Buffer.from(`${index+1} 0 obj\n`,"binary"),object,Buffer.from("\nendobj\n","binary")]);parts.push(wrapped);offset+=wrapped.length});const xrefOffset=offset,xref=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(value=>`${String(value).padStart(10,"0")} 00000 n `).join("\n")}\ntrailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;parts.push(Buffer.from(xref,"binary"));return Buffer.concat(parts)}
