import type {Metadata} from "next";
import {mediaRepository} from "@/repositories/media.repository";
import {VideoGallery} from "@/components/public/video-gallery";
import {ListingFilters} from "@/components/public/listing-filters";
import {CharacterFilter} from "@/components/public/character-filter";
import {EmptyState,Pagination} from "@/components/ui";

export const metadata:Metadata={title:"Creative videos for children",description:"Watch creative activities, coloring and behind-the-scenes videos.",alternates:{canonical:"/en/videos",languages:{fr:"/videos",en:"/en/videos"}}};
export default async function EnglishVideosPage({searchParams}:{searchParams:Promise<{page?:string;q?:string;category?:string;character?:string;sort?:string}>}){const s=await searchParams,sort=s.sort==="oldest"?"oldest":"newest",[r,categories,characters]=await Promise.all([mediaRepository.paginatedPublishedVideos({page:Number(s.page)||1,pageSize:9,search:s.q,category:s.category,character:s.character,sort,language:"EN"}),mediaRepository.videoCategoryOptions("EN"),mediaRepository.videoCharacterOptions("EN")]),items=r.items.map(({vlog,video,thumbnail})=>({id:vlog.id,title:vlog.title,description:vlog.description,duration:vlog.duration,path:video?.path??null,mimeType:video?.mimeType??null,thumbnailPath:thumbnail?.path??null}));return <section className="container py-8"><header className="mb-6"><p className="text-xs font-black uppercase tracking-[.2em] text-primary">Watch together</p><h1 className="mt-2 font-display text-4xl font-black">Creativity comes to life</h1><p className="mt-2 text-foreground/60">Coloring, activities and studio stories in a joyful format.</p></header><ListingFilters locale="en" title="Find a video" query={s.q} category={s.category} sort={sort} categories={categories} searchPlaceholder="Search videos…"/><CharacterFilter options={characters} selected={s.character} path="/en/videos" query={{q:s.q,category:s.category,sort}} locale="en" kind="videos"/><p className="mb-4 text-sm font-semibold text-foreground/60">{r.total} video{r.total===1?"":"s"} found</p>{items.length?<VideoGallery items={items}/>:<EmptyState locale="en" title="No English videos yet"/>}<Pagination locale="en" page={r.page} pages={r.pages} path="/en/videos" query={{q:s.q,category:s.category,character:s.character,sort}}/></section>}
