import { ActivityCard } from "@/components/content-cards";
import type { Metadata } from "next";
import { EmptyState, Pagination } from "@/components/ui";
import { FileDown, Sparkles } from "lucide-react";
import { hasClubAccess } from "@/lib/club-access";
import { contentRepository } from "@/repositories/content.repository";
import { ListingFilters } from "@/components/public/listing-filters";

export const metadata: Metadata = { title: "Activités gratuites à imprimer pour enfants", description: "Téléchargez des coloriages, jeux et activités éducatives gratuites en PDF pour occuper les enfants loin des écrans.", alternates: { canonical: "/activites" }, openGraph: { url: "/activites", title: "PDF et activités gratuites à imprimer", description: "Des activités créatives gratuites pour jouer et apprendre en famille." } };

export default async function ActivitiesPage({ searchParams }: { searchParams: Promise<{ page?: string; q?: string;category?:string;type?:string;sort?:string }> }) {
  const search = await searchParams;
  const sort=search.sort==="oldest"?"oldest":"newest";
  const [result, clubUnlocked,categories,activityTypes] = await Promise.all([contentRepository.activities({ page: Number(search.page) || 1, search: search.q,category:search.category,activityType:search.type,sort, pageSize: 24 }), hasClubAccess(),contentRepository.activityCategoryOptions(),contentRepository.activityTypeOptions()]);
  return <section className="relative min-h-[calc(100vh-4rem)] overflow-hidden bg-gradient-to-b from-emerald-50/40 to-background py-6 dark:from-[#111a18] dark:via-[#121a19] dark:to-background md:py-8"><div className="pointer-events-none absolute -left-24 -top-20 size-64 rounded-full bg-orange-200/20 blur-3xl dark:bg-orange-400/10"/><div className="container relative"><header className="mb-5 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><span className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[.18em] text-primary md:text-xs"><Sparkles size={14}/> À vos crayons</span><h1 className="mt-2 font-display text-3xl font-black leading-tight md:text-4xl">Des activités gratuites <span className="text-primary">à imprimer.</span></h1><p className="mt-1.5 text-sm text-foreground/60 md:text-base">Quelques minutes d’impression, des heures de créativité.</p></div><div className="inline-flex w-fit items-center gap-2.5 rounded-2xl border bg-card/85 px-3 dark:border-white/10 dark:bg-white/5 py-2 shadow-sm"><FileDown className="text-primary" size={18}/><strong className="text-lg leading-none">{result.total}</strong><span className="text-xs font-semibold text-foreground/55">activité{result.total>1?"s":""}</span></div></header><ListingFilters title="Trouver une activité" query={search.q} category={search.category} activityType={search.type} sort={sort} categories={categories} activityTypes={activityTypes} searchPlaceholder="Rechercher une activité…"/><p className="mb-4 text-sm font-semibold text-foreground/60">{result.total} activité{result.total>1?"s":""} trouvée{result.total>1?"s":""}</p><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{result.items.length ? result.items.map((item, index) => <ActivityCard key={item.id} item={item} index={index} clubUnlocked={clubUnlocked}/>) : <EmptyState/>}</div><Pagination page={result.page} pages={result.pages} path="/activites" query={{q:search.q,category:search.category,type:search.type,sort}}/></div></section>;
}
