import type {Metadata} from "next";
import {contentRepository} from "@/repositories/content.repository";
import {BookCard} from "@/components/content-cards";
import {BookFilters} from "@/components/public/book-filters";
import {EmptyState,Pagination} from "@/components/ui";

export const metadata:Metadata={title:"Coloring and activity books for children",description:"Discover creative coloring books, educational games and activity books for children.",alternates:{canonical:"/en/books",languages:{fr:"/livres",en:"/en/books"}}};
type Params={page?:string;q?:string;category?:string;type?:string;pricing?:string;sort?:string};
export default async function EnglishBooksPage({searchParams}:{searchParams:Promise<Params>}){const s=await searchParams,pricing=s.pricing==="FREE"||s.pricing==="PAID"?s.pricing:undefined,sort=s.sort==="oldest"?"oldest":"newest",[r,categories,activityTypes]=await Promise.all([contentRepository.books({page:Number(s.page)||1,search:s.q,category:s.category,activityType:s.type,pricing,sort,pageSize:12,language:"EN"}),contentRepository.bookCategories("EN"),contentRepository.activityTypeOptions("EN")]);return <div className="container py-6 md:py-8"><header className="mb-5"><p className="text-xs font-black uppercase tracking-[.2em] text-primary md:text-sm">The library</p><div className="mt-2 flex flex-col gap-2 lg:flex-row lg:items-end lg:justify-between lg:gap-8"><h1 className="text-balance font-display text-3xl font-black leading-[1.05] tracking-tight md:text-4xl">Books that spark imagination</h1><p className="text-sm font-semibold text-foreground/60 md:text-base">Coloring, games and adventures for every age.</p></div></header><BookFilters activityType={s.type} activityTypes={activityTypes} locale="en" query={s.q} category={s.category} pricing={pricing} sort={sort} categories={categories}/><p className="mb-4 text-sm font-semibold text-foreground/60">{r.total} book{r.total===1?"":"s"} found</p><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{r.items.length?r.items.map((x,i)=><BookCard locale="en" key={x.book.id} item={x.book} category={x.category} coverPath={x.cover?.path} gallery={x.gallery} index={i}/>):<EmptyState locale="en" title="No English books yet"/>}</div><Pagination locale="en" page={r.page} pages={r.pages} path="/en/books" query={{q:s.q,category:s.category,type:s.type,pricing,sort}}/></div>}
