"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Activity, BookOpen, ChevronDown, Database, DatabaseBackup, FileText, Film, ImageIcon, KeyRound, Search, ShieldCheck, Sparkles, Tags } from "lucide-react";

const sections = [
  { id: "demarrage", title: "Bien démarrer", icon: Sparkles, intro: "Les premiers repères pour administrer le site sans risque.", steps: ["Connectez-vous depuis /connexion avec le compte administrateur.", "Utilisez le menu latéral pour accéder aux différents contenus.", "Vérifiez le Dashboard pour contrôler les contenus, les visites et le stockage.", "Déconnectez-vous lorsque vous utilisez un ordinateur partagé."], tips: ["Les modifications publiées deviennent visibles sur le site.", "Préparez vos textes et images avant de commencer une création."] },
  { id: "postgresql", title: "Base PostgreSQL", icon: Database, intro: "Comprendre où sont stockées les données et comment appliquer les évolutions.", steps: ["PostgreSQL stocke les comptes, livres, catégories, articles, réglages et métadonnées des médias.", "Les images, vidéos et PDF restent dans le répertoire MEDIA_ROOT : ils ne sont pas enregistrés dans PostgreSQL.", "Le schéma Drizzle décrit les 18 tables et leurs relations dans src/db/schema.ts.", "Après une évolution du schéma, générez une migration avec npm run db:generate puis appliquez-la avec npm run db:migrate.", "Utilisez pgAdmin ou npm run db:studio pour consulter les données sans modifier manuellement la structure."], tips: ["npm run db:seed initialise seulement l’administrateur et les réglages manquants.", "Une erreur 28P01 indique généralement un mot de passe incorrect dans DATABASE_URL.", "Une erreur relation does not exist indique généralement que les migrations n’ont pas été appliquées."] },
  { id: "livres", title: "Livres et galeries", icon: BookOpen, intro: "Créer un livre, sa couverture et les médias qui lui sont associés.", steps: ["Ouvrez Livres, puis cliquez sur Ajouter.", "Renseignez le titre, les âges, le nombre de pages, la catégorie et la description Markdown.", "Indiquez si le livre est gratuit ou payant. Pour un livre payant, le prix Amazon reste facultatif et indicatif.", "Ajoutez une couverture carrée, les images de la galerie et, si besoin, une vidéo MP4 de présentation.", "Dans Médias liés aux livres, vous pouvez ajouter, remplacer ou retirer la vidéo d’un livre existant.", "Vérifiez l’aperçu, l’ordre des images et le lien Amazon.", "Activez la publication lorsque la fiche est prête."], tips: ["La couverture présente le livre dans la liste.", "La galerie permet au visiteur de feuilleter quelques pages avant d’aller sur Amazon.", "La vidéo est liée à un seul livre et apparaît sur sa fiche détaillée publique.", "Actualisez le prix indicatif après un changement sur Amazon : sa date de vérification est affichée aux visiteurs.", "La liste publique peut être filtrée par catégorie, gratuit ou payant, et triée par date."] },
  { id: "activites", title: "Activités et PDF", icon: Activity, intro: "Créer des documents gratuits ou réservés au Club Instagram.", steps: ["Créez d’abord les catégories utiles depuis l’onglet Catégories.", "Ouvrez Activités et choisissez Convertir en PDF et ajouter.", "Ajoutez les images dans l’ordre souhaité : chaque image devient une page du PDF.", "Choisissez une couverture puis cochez une ou plusieurs catégories.", "Sélectionnez l’accès Public ou Club Instagram et créez l’activité.", "Dans la liste, utilisez la recherche ou le filtre par catégorie, puis modifiez, téléchargez, publiez, masquez ou supprimez l’activité."], tips: ["Une activité peut appartenir à plusieurs catégories.", "Le PDF et sa couverture restent directement attachés à l’activité.", "Les livres, images et vidéos ne sont plus associés aux activités.", "Le téléchargement reste disponible directement depuis la liste publique des activités."] },
  { id: "categories", title: "Catégories d’activités", icon: Tags, intro: "Organiser les activités avec des couleurs et des badges personnalisés.", steps: ["Ouvrez Catégories dans le menu du back-office.", "Cliquez sur Nouvelle catégorie et renseignez son nom et sa description.", "Choisissez une couleur facilement reconnaissable.", "Ajoutez un badge court ou un emoji, puis vérifiez son aperçu.", "Utilisez l’œil pour consulter, le crayon pour modifier et la poubelle pour supprimer.", "Ouvrez ensuite Activités pour cocher les catégories adaptées à chaque PDF."], tips: ["La couleur et le badge apparaissent dans la liste des activités.", "Supprimer une catégorie retire uniquement ses associations : les activités et leurs PDF sont conservés.", "Une catégorie peut être utilisée par plusieurs activités."] },
  { id: "images-videos", title: "Images et vidéos", icon: ImageIcon, intro: "Présenter les créations visuelles sans proposer leur téléchargement.", steps: ["Ouvrez Images ou Vidéos puis cliquez sur Ajouter.", "Choisissez un fichier optimisé et ajoutez une description utile.", "Publiez le contenu lorsqu’il est prêt.", "Utilisez l’œil pour consulter, le crayon pour modifier et la poubelle pour supprimer."], tips: ["Les images du site doivent être différentes des pages PDF téléchargeables.", "Compressez les vidéos avant l’envoi pour économiser le volume de stockage."] },
  { id: "blog", title: "Articles de blog", icon: FileText, intro: "Publier des articles prêts à être lus et bien structurés.", steps: ["Ouvrez Blog puis Ajouter.", "Renseignez le titre, le résumé, l’auteur et la couverture.", "Collez ou rédigez le contenu au format Markdown.", "Utilisez l’aperçu avant publication pour vérifier titres, listes et liens.", "Publiez l’article lorsque la mise en page est correcte."], tips: ["Utilisez ## pour un sous-titre et **texte** pour du gras.", "Chaque article contient automatiquement un lien vers la liste des livres."] },
  { id: "club", title: "Club Instagram", icon: KeyRound, intro: "Donner temporairement accès aux PDF réservés aux abonnés.", steps: ["Vérifiez manuellement que la personne suit votre compte Instagram.", "Ouvrez Codes d’accès et générez un nouveau code.", "Choisissez sa durée d’utilisation et la durée de l’accès accordé.", "Copiez le code immédiatement et envoyez-le en message privé.", "Désactivez ou supprimez le code en cas d’erreur."], tips: ["Un Pass Instagram est différent d’un code de récupération administrateur.", "N’envoyez jamais vos codes de récupération de sécurité à un abonné."] },
  { id: "sauvegarde", title: "Dashboard, stockage et sauvegarde", icon: DatabaseBackup, intro: "Surveiller le site et conserver une copie récupérable des données.", steps: ["Consultez l’état PostgreSQL, le volume des médias et l’espace disque depuis le Dashboard.", "Contrôlez les visiteurs uniques par jour et par mois.", "Planifiez scripts/backup-db.sh et scripts/backup-uploads.sh chaque nuit avec cron sur le VPS.", "Conservez une copie chiffrée des archives sur un stockage externe.", "Testez périodiquement scripts/restore-db.sh sur une installation non productive."], tips: ["PostgreSQL et les médias sont deux sauvegardes différentes et toutes deux indispensables.", "Une sauvegarde présente uniquement sur le VPS ne protège pas contre la perte du serveur.", "Une restauration de production se fait depuis le terminal du VPS, jamais depuis le navigateur."] },
  { id: "securite", title: "Compte et sécurité", icon: ShieldCheck, intro: "Protéger le seul accès administrateur et récupérer le compte.", steps: ["Utilisez un mot de passe long et unique.", "Après 5 échecs, le compte est bloqué pendant 15 minutes.", "Générez les 8 codes de récupération depuis Sécurité.", "Conservez le PDF imprimé dans un lieu sûr et séparé de l’ordinateur.", "Consultez régulièrement le journal de sécurité pour repérer une activité inhabituelle."], tips: ["Chaque code de récupération fonctionne une seule fois.", "Une nouvelle génération annule immédiatement tous les anciens codes."] },
  { id: "referencement", title: "Référencement Google", icon: Search, intro: "Aider les parents à trouver le site depuis leurs recherches.", steps: ["Donnez à chaque livre et article un titre précis qui correspond à une recherche réelle.", "Rédigez une description unique, utile et naturelle sans répéter artificiellement les mots-clés.", "Ajoutez une couverture de qualité et une description pertinente à chaque image.", "Publiez régulièrement des articles qui répondent aux questions des parents.", "Après la mise en ligne, validez le domaine dans Google Search Console et soumettez /sitemap.xml."], tips: ["Le référencement progresse sur plusieurs semaines ou plusieurs mois.", "Un contenu utile et partagé sur Instagram vaut mieux qu’une accumulation de mots-clés."] },
  { id: "production", title: "Mise en production OVH", icon: Film, intro: "Les contrôles essentiels avant et après la publication du site.", steps: ["PostgreSQL fonctionne comme service local du VPS et n’expose jamais le port 5432 sur Internet.", "PM2 exécute Next.js sur 127.0.0.1:3000 et redémarre l’application automatiquement.", "Caddy expose uniquement les ports 80 et 443, gère HTTPS et transmet les requêtes à Next.js.", "Avant une mise à jour, sauvegardez PostgreSQL et les médias, puis lancez scripts/deploy.sh.", "Après le déploiement, contrôlez /api/health, la connexion, les médias et un téléchargement PDF."], tips: ["Ne copiez jamais le fichier .env local sur Git.", "Le pare-feu doit autoriser uniquement SSH, HTTP et HTTPS.", "Consultez pm2 logs lepetitcrayon et systemctl status caddy postgresql en cas de panne."] },
];

export function AdminGuide() {
  const [query, setQuery] = useState(""), [open, setOpen] = useState<string[]>(["demarrage"]);
  useEffect(() => { const id = window.location.hash.slice(1); if (sections.some(section => section.id === id)) setOpen(values => values.includes(id) ? values : [...values, id]); }, []);
  const results = useMemo(() => { const normalized = query.trim().toLocaleLowerCase("fr"); return normalized ? sections.filter(section => `${section.title} ${section.intro} ${section.steps.join(" ")} ${section.tips.join(" ")}`.toLocaleLowerCase("fr").includes(normalized)) : sections; }, [query]);
  const toggle = (id: string) => setOpen(values => values.includes(id) ? values.filter(value => value !== id) : [...values, id]);
  return <div className="mx-auto max-w-6xl"><header className="rounded-[2rem] bg-[#173f34] p-7 text-white shadow-xl sm:p-10"><p className="text-xs font-black uppercase tracking-[.22em] text-emerald-200">Centre d’aide</p><h1 className="mt-3 text-3xl font-black sm:text-4xl">Guide du back-office</h1><p className="mt-3 max-w-2xl leading-relaxed text-emerald-50/75">Retrouvez rapidement les étapes utiles pour publier, organiser, sécuriser et sauvegarder le site Le Petit Crayon.</p><label className="relative mt-7 block max-w-2xl"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={20}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Rechercher : catégorie, livre, PDF, sauvegarde…" className="min-h-14 w-full rounded-2xl border-0 bg-white pl-12 pr-4 font-semibold text-slate-950 outline-none ring-4 ring-white/10 placeholder:text-slate-400"/></label></header>
    {!query && <nav aria-label="Sommaire du guide" className="mt-6 flex gap-2 overflow-x-auto pb-2">{sections.map(section => <Link key={section.id} href={`#${section.id}`} onClick={() => setOpen(values => values.includes(section.id) ? values : [...values, section.id])} className="whitespace-nowrap rounded-full border bg-white px-4 py-2 text-sm font-bold text-slate-600 transition hover:border-emerald-300 hover:text-emerald-700">{section.title}</Link>)}</nav>}
    <div className="mt-6 space-y-4">{results.map(section => { const Icon = section.icon, expanded = open.includes(section.id) || Boolean(query); return <section id={section.id} key={section.id} className="scroll-mt-6 overflow-hidden rounded-[1.5rem] border bg-white shadow-sm"><button aria-expanded={expanded} onClick={() => toggle(section.id)} className="flex w-full items-center gap-4 p-5 text-left sm:p-6"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-emerald-50 text-emerald-700"><Icon size={23}/></span><span className="min-w-0 flex-1"><span className="block text-lg font-black text-slate-950">{section.title}</span><span className="mt-1 block text-sm text-slate-500">{section.intro}</span></span><ChevronDown className={`shrink-0 text-slate-400 transition ${expanded ? "rotate-180" : ""}`}/></button>{expanded && <div className="border-t bg-slate-50/60 p-5 sm:p-6"><ol className="space-y-4">{section.steps.map((step, index) => <li key={step} className="flex gap-3"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-slate-950 text-xs font-black text-white">{index + 1}</span><span className="pt-0.5 text-sm leading-relaxed text-slate-700">{step}</span></li>)}</ol><div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4"><p className="text-xs font-black uppercase tracking-wider text-amber-800">Bon à savoir</p><ul className="mt-2 space-y-1 text-sm text-amber-900">{section.tips.map(tip => <li key={tip}>• {tip}</li>)}</ul></div></div>}</section>; })}{results.length === 0 && <div className="grid min-h-52 place-items-center rounded-[1.5rem] border border-dashed bg-white text-center"><div><Search className="mx-auto text-slate-300" size={36}/><p className="mt-3 font-black">Aucun résultat</p><p className="mt-1 text-sm text-slate-500">Essayez un terme plus simple.</p></div></div>}</div>
  </div>;
}
