import { BookOpen, CheckCircle2, FileText, Film, HardDrive, ImageIcon, ServerCog } from "lucide-react";

type Counts = { books:number; images:number; videos:number; pdf:number };
type Sizes = { database:number; images:number; videos:number; pdf:number };
type Disk = { total:number; used:number; available:number; isProduction:boolean };

export function BackupSettings({ sizes, counts, storageCapacity, databaseIntegrity, hostingProvider, disk }: { sizes:Sizes; counts:Counts; storageCapacity:number; databaseIntegrity:boolean; hostingProvider:string; disk:Disk }) {
  const totalMedia=sizes.images+sizes.videos+sizes.pdf;
  const totalUsed=sizes.database+totalMedia;
  const siteUsage=Math.min(100,totalUsed/storageCapacity*100);

  return <div className="space-y-6">
    <section className="rounded-[1.75rem] border border-slate-200 bg-white p-6 shadow-sm dark:border-white/10 dark:bg-slate-900/55 md:p-8">
      <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700 dark:text-emerald-400">Vue d’ensemble</p><h2 className="mt-2 text-2xl font-black text-slate-950 dark:text-slate-50">Contenu du site</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Comptages PostgreSQL et tailles réelles des fichiers rapportés au stockage configuré.</p></div><p className="rounded-full bg-slate-100 px-4 py-2 text-xs font-bold text-slate-500 dark:bg-white/[.07] dark:text-slate-300">Médias : {formatBytes(totalMedia)}</p></div>
      <div className="mt-8 grid items-stretch gap-5 lg:grid-cols-[minmax(320px,.65fr)_minmax(0,1.35fr)]">
        <DatabaseHealth sitePercent={siteUsage} siteUsed={totalUsed} planCapacity={storageCapacity} databaseSize={sizes.database} integrity={databaseIntegrity} hostingProvider={hostingProvider} disk={disk}/>
        <div className="grid grid-cols-2 gap-4">
          <CircleStat label="Livres" value={counts.books} color="#0f766e" soft="#ccfbf1" icon={<BookOpen size={19}/>}/>
          <CircleStat label="Images" value={counts.images} color="#2563eb" soft="#dbeafe" icon={<ImageIcon size={19}/>}/>
          <CircleStat label="Vidéos" value={counts.videos} color="#7c3aed" soft="#ede9fe" icon={<Film size={19}/>}/>
          <CircleStat label="PDF" value={counts.pdf} color="#d97706" soft="#fef3c7" icon={<FileText size={19}/>}/>
        </div>
      </div>
    </section>

    <section className="rounded-[1.75rem] border border-blue-200 bg-blue-50 p-7">
      <div className="flex gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-blue-100 text-blue-700"><ServerCog/></span><div><h2 className="text-xl font-black text-blue-950">Sauvegardes administrées sur le VPS</h2><p className="mt-2 text-sm leading-relaxed text-blue-900/75">PostgreSQL et les fichiers sont sauvegardés séparément avec les scripts sécurisés du serveur. Utilisez <code>scripts/backup-db.sh</code> et <code>scripts/backup-uploads.sh</code>, puis copiez les archives vers un stockage externe chiffré. Une restauration de production n’est volontairement pas proposée depuis le navigateur.</p></div></div>
    </section>
  </div>;
}

function CircleStat({label,value,color,soft,icon}:{label:string;value:number;color:string;soft:string;icon:React.ReactNode}){const progress=Math.min(100,value?Math.max(12,value*8):0);return <div className="rounded-2xl border border-slate-200 p-4 text-center dark:border-white/10 dark:bg-white/[.025]"><div className="relative mx-auto size-24"><Ring percent={progress} color={color} track={soft}/><span className="absolute inset-0 grid place-items-center"><span style={{color}}>{icon}</span></span></div><p className="mt-3 text-2xl font-black text-slate-900 dark:text-slate-50">{value}</p><p className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">{label}</p></div>}
function DatabaseHealth({sitePercent,siteUsed,planCapacity,databaseSize,integrity,hostingProvider,disk}:{sitePercent:number;siteUsed:number;planCapacity:number;databaseSize:number;integrity:boolean;hostingProvider:string;disk:Disk}){const diskPercent=disk.total?Math.min(100,disk.used/disk.total*100):0,color=diskPercent>=85?"#dc2626":diskPercent>=70?"#d97706":"#16a34a";return <div className="flex h-full min-h-72 flex-col items-center justify-center rounded-[1.5rem] border border-emerald-100 bg-gradient-to-br from-emerald-50/80 via-white to-white p-6 text-center shadow-sm dark:border-emerald-400/20 dark:from-emerald-950/55 dark:via-slate-900 dark:to-slate-900"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700 dark:text-emerald-400">{disk.isProduction?`Stockage ${hostingProvider}`:"Disque de développement local"}</p><div className="relative mt-5 size-44"><Ring percent={diskPercent} color={color} track="#dcfce7" trackClassName="dark:stroke-emerald-950"/><span className="absolute inset-0 grid place-items-center"><span><HardDrive size={23} className="mx-auto mb-2 text-slate-400 dark:text-slate-500"/><strong className="block text-3xl font-black text-slate-900 dark:text-slate-50">{formatPercent(diskPercent)}</strong><small className="font-bold text-slate-400 dark:text-slate-500">du disque utilisé</small></span></span></div><p className="mt-4 text-xs font-semibold text-slate-500 dark:text-slate-300">{formatBytes(disk.used)} utilisés sur {formatBytes(disk.total)} · {formatBytes(disk.available)} libres</p><div className="mt-4 w-full rounded-xl border border-slate-100 bg-white/80 p-3 text-left text-xs dark:border-white/10 dark:bg-black/20"><div className="flex justify-between gap-3"><span className="text-slate-500 dark:text-slate-400">Contenus du site</span><strong className="text-slate-900 dark:text-slate-100">{formatBytes(siteUsed)}</strong></div><div className="mt-1.5 flex justify-between gap-3"><span className="text-slate-500 dark:text-slate-400">Part du stockage configuré ({formatBytes(planCapacity)})</span><strong className="text-slate-900 dark:text-slate-100">{formatPercent(sitePercent)}</strong></div></div><div className={`mt-3 inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-[11px] font-black ${integrity?"bg-emerald-100 text-emerald-700 dark:bg-emerald-400/15 dark:text-emerald-300":"bg-red-100 text-red-700 dark:bg-red-400/15 dark:text-red-300"}`}><CheckCircle2 size={14}/> PostgreSQL {integrity?"accessible":"à vérifier"} · {formatBytes(databaseSize)}</div></div>}
function Ring({percent,color,track,trackClassName}:{percent:number;color:string;track:string;trackClassName?:string}){const radius=40,circumference=2*Math.PI*radius;return <svg viewBox="0 0 100 100" className="size-full -rotate-90"><circle cx="50" cy="50" r={radius} fill="none" stroke={track} strokeWidth="9" className={trackClassName}/><circle cx="50" cy="50" r={radius} fill="none" stroke={color} strokeWidth="9" strokeLinecap="round" strokeDasharray={circumference} strokeDashoffset={circumference*(1-percent/100)} className="transition-all duration-700"/></svg>}
function formatBytes(bytes:number){if(!bytes)return"0 o";const units=["o","Ko","Mo","Go"],index=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),units.length-1);return`${(bytes/1024**index).toFixed(index?1:0)} ${units[index]}`}
function formatPercent(value:number){if(value>0&&value<0.01)return"< 0,01 %";return`${value.toLocaleString("fr-FR",{minimumFractionDigits:value<1?2:0,maximumFractionDigits:value<1?2:1})} %`}
