"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, FileText, ImagePlus, LoaderCircle, Plus, Save, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { AdminFormField } from "./admin-form-field";
import { AdminSelect } from "./admin-select";
import { MarkdownEditor } from "./markdown-editor";

type Category={id:string;language:"FR"|"EN";name:string;badge:string};
const input="mt-2 min-h-12 w-full rounded-2xl border border-slate-200 bg-white px-4 text-slate-950 outline-none transition focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10 dark:border-white/10 dark:bg-slate-950/45 dark:text-white dark:focus:ring-emerald-500/15";

export function BlogCreatePage(){
  const router=useRouter();
  const[categories,setCategories]=useState<Category[]>([]),[language,setLanguage]=useState<"FR"|"EN">("FR"),[categoryId,setCategoryId]=useState(""),[content,setContent]=useState(""),[cover,setCover]=useState<File|null>(null),[preview,setPreview]=useState<string|null>(null),[submitting,setSubmitting]=useState(false),[error,setError]=useState("");
  useEffect(()=>{fetch("/api/admin/categories",{cache:"no-store"}).then(async response=>{if(!response.ok)throw new Error();return response.json() as Promise<{items:Category[]}>}).then(data=>setCategories(data.items)).catch(()=>setError("Impossible de charger les catégories."))},[]);
  useEffect(()=>{if(!cover){setPreview(null);return}const url=URL.createObjectURL(cover);setPreview(url);return()=>URL.revokeObjectURL(url)},[cover]);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(submitting)return;setSubmitting(true);setError("");const form=new FormData(event.currentTarget);form.set("content",content);if(!cover)form.delete("cover");const response=await fetch("/api/admin/posts",{method:"POST",body:form}),data=await response.json().catch(()=>null) as {message?:string}|null;if(response.ok){router.push("/admin/blog");router.refresh();return}setError(data?.message||"Création impossible.");setSubmitting(false)}
  const availableCategories=categories.filter(item=>item.language===language);
  return <div className="mx-auto max-w-7xl pb-8">
    <header className="mb-5 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Link href="/admin/blog" className="inline-flex items-center gap-2 text-sm font-black text-slate-500 transition hover:text-emerald-700 dark:text-slate-400 dark:hover:text-emerald-300"><ArrowLeft size={17}/>Retour au blog</Link><p className="mt-5 text-xs font-black uppercase tracking-[.2em] text-emerald-700 dark:text-emerald-300">Éditeur du blog</p><h1 className="mt-1 text-3xl font-black tracking-tight text-slate-950 dark:text-white sm:text-4xl">Créer un article</h1><p className="mt-2 text-slate-500 dark:text-slate-400">Préparez le contenu, vérifiez son aperçu puis publiez-le.</p></div><span className="hidden size-14 place-items-center rounded-2xl bg-emerald-100 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300 sm:grid"><Sparkles size={25}/></span></header>
    <form onSubmit={submit} className="blog-create-page grid items-start gap-5 lg:grid-cols-[minmax(20rem,.78fr)_minmax(0,1.22fr)]">
      <section className="blog-article-details grid gap-4 rounded-[1.75rem] border border-emerald-100 bg-gradient-to-br from-emerald-50/60 via-white to-slate-50 p-4 shadow-sm dark:border-emerald-400/15 dark:from-emerald-950/15 dark:via-slate-900 dark:to-slate-950/40 sm:p-6 lg:sticky lg:top-5">
        <div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-emerald-100 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300"><FileText size={20}/></span><div><h2 className="font-black text-slate-950 dark:text-white">Informations</h2><p className="text-xs text-slate-500 dark:text-slate-400">Identité et classement</p></div></div>
        <div className="grid gap-4 sm:grid-cols-[10rem_1fr] lg:grid-cols-1 xl:grid-cols-[10rem_1fr]"><AdminFormField label="Langue"><select name="language" className={input} value={language} onChange={event=>{setLanguage(event.target.value as "FR"|"EN");setCategoryId("")}}><option value="FR">🇫🇷 Français</option><option value="EN">🇬🇧 English</option></select></AdminFormField><AdminFormField label="Titre"><input name="title" className={input} required minLength={2} maxLength={150} placeholder={language==="EN"?"Article title":"Titre de l’article"}/></AdminFormField></div>
        <AdminFormField label="Auteur"><input name="authorName" className={input} defaultValue="Le Petit Crayon" required minLength={2} maxLength={100}/></AdminFormField>
        <div><input type="hidden" name="categoryId" value={categoryId}/><AdminSelect label="Catégorie de l’article" value={categoryId} options={[{value:"",label:"Sans catégorie"},...availableCategories.map(item=>({value:item.id,label:`${item.badge} ${item.name}`}))]} onChange={setCategoryId}/></div>
        <AdminFormField label="Résumé"><textarea name="excerpt" className={`${input} min-h-28 py-3`} required minLength={10} maxLength={300} placeholder={language==="EN"?"A short, engaging introduction…":"Une introduction courte et engageante…"}/></AdminFormField>
        <div className="rounded-2xl border border-dashed border-emerald-300 bg-white/75 p-3 dark:border-emerald-400/25 dark:bg-slate-950/30"><label className="flex cursor-pointer items-center gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-emerald-100 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300"><ImagePlus size={20}/></span><span className="min-w-0 flex-1"><strong className="block text-sm text-slate-950 dark:text-white">Image de couverture</strong><span className="block truncate text-xs text-slate-500 dark:text-slate-400">{cover?.name||"JPG, PNG, WebP ou AVIF"}</span></span><input name="cover" type="file" accept="image/jpeg,image/png,image/webp,image/avif" className="sr-only" onChange={event=>setCover(event.target.files?.[0]??null)}/></label>{preview&&<div className="relative mt-3 aspect-[16/9] overflow-hidden rounded-xl bg-slate-100 dark:bg-slate-950"><Image unoptimized fill src={preview} alt="Aperçu de la couverture" className="object-cover"/></div>}</div>
        <div className="grid gap-2 rounded-2xl border border-slate-200 bg-white/75 p-3 dark:border-white/10 dark:bg-white/[.035] sm:grid-cols-2 lg:grid-cols-1 xl:grid-cols-2"><label className="flex min-h-11 cursor-pointer items-center gap-3 rounded-xl px-2 text-sm font-bold hover:bg-emerald-50 dark:hover:bg-emerald-400/[.07]"><input type="checkbox" name="published" className="size-5 accent-emerald-700"/>Publier immédiatement</label><label className="flex min-h-11 cursor-pointer items-center gap-3 rounded-xl px-2 text-sm font-bold hover:bg-amber-50 dark:hover:bg-amber-400/[.07]"><input type="checkbox" name="featured" className="size-5 accent-amber-500"/>Mettre à la une</label></div>
      </section>
      <section className="min-w-0 rounded-[1.75rem] border border-slate-200 bg-white p-4 shadow-sm dark:border-white/10 dark:bg-slate-900 sm:p-6"><div className="mb-4"><h2 className="text-lg font-black text-slate-950 dark:text-white">Contenu de l’article</h2><p className="text-sm text-slate-500 dark:text-slate-400">Rédigez en Markdown et contrôlez le rendu avec l’aperçu.</p></div><MarkdownEditor name="content" value={content} onChange={setContent}/><div className="mt-4 rounded-xl border border-emerald-100 bg-emerald-50/60 px-4 py-3 text-xs leading-6 text-slate-600 dark:border-emerald-400/20 dark:bg-emerald-400/[.06] dark:text-slate-300"><strong className="text-emerald-800 dark:text-emerald-300">Markdown :</strong> <code># Titre</code> · <code>**gras**</code> · <code>- liste</code> · <code>[lien](https://…)</code></div></section>
      {error&&<p role="alert" className="rounded-2xl bg-red-50 p-4 text-sm font-bold text-red-700 dark:bg-red-500/10 dark:text-red-300 lg:col-span-2">{error}</p>}
      <footer className="flex items-center justify-end gap-3 pt-1 lg:col-span-2"><Link href="/admin/blog" className="group inline-flex min-h-12 items-center justify-center rounded-2xl border border-slate-200 bg-white px-5 font-black text-slate-600 shadow-sm transition duration-200 hover:-translate-y-1 hover:border-rose-300 hover:bg-rose-50 hover:text-rose-700 hover:shadow-lg hover:shadow-rose-900/10 active:translate-y-0 active:scale-95 dark:border-white/10 dark:bg-white/[.035] dark:text-slate-300 dark:hover:border-rose-400/30 dark:hover:bg-rose-400/10 dark:hover:text-rose-300">Annuler</Link><button disabled={submitting} className="group inline-flex min-h-12 items-center justify-center gap-2 overflow-hidden rounded-2xl border border-emerald-500/20 bg-gradient-to-r from-emerald-700 to-teal-700 px-6 font-black text-white shadow-lg shadow-emerald-950/20 transition duration-200 hover:-translate-y-1 hover:from-emerald-600 hover:to-teal-500 hover:shadow-xl hover:shadow-emerald-900/30 active:translate-y-0 active:scale-95 disabled:pointer-events-none disabled:opacity-60">{submitting?<LoaderCircle className="animate-spin" size={18}/>:<Save size={18} className="transition-transform duration-200 group-hover:-rotate-6 group-hover:scale-110"/>} {submitting?"Création…":"Créer l’article"}</button></footer>
    </form>
  </div>
}
