"use client";

import Image from "next/image";
import Link from "next/link";
import { AlertTriangle, CheckCircle2, ChevronDown, ChevronUp, Eye, FileText, LoaderCircle, Pencil, Plus, RefreshCw, Search, Star, Tags, Trash2, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { htmlToMarkdown } from "@/lib/rich-text";
import { MarkdownEditor } from "./markdown-editor";
import { SiblingPagination } from "@/components/client-pagination";
import { AdminSelect } from "./admin-select";
import { AdminFormField } from "./admin-form-field";

type Post={id:string;slug:string;language:"FR"|"EN";title:string;excerpt:string;content:string;authorName:string;categoryId:string|null;published:boolean;featured:boolean;createdAt:string;updatedAt:string};
type Row={post:Post;cover:{path:string;alt:string|null}|null};
type Edit=Omit<Post,"slug"|"createdAt"|"updatedAt">;
type Category={id:string;name:string;color:string;badge:string};

export function BlogManager(){
  const[items,setItems]=useState<Row[]>([]),[categories,setCategories]=useState<Category[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[categoryFilter,setCategoryFilter]=useState(""),[expanded,setExpanded]=useState<string|null>(null),[creating,setCreating]=useState(false),[editing,setEditing]=useState<Edit|null>(null),[pendingDelete,setPendingDelete]=useState<Row|null>(null),[success,setSuccess]=useState(""),[error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);const[response,categoryResponse]=await Promise.all([fetch("/api/admin/posts",{cache:"no-store"}),fetch("/api/admin/blog-categories",{cache:"no-store"})]);if(response.ok)setItems(((await response.json())as{items:Row[]}).items);if(categoryResponse.ok)setCategories(((await categoryResponse.json())as{items:Category[]}).items);setLoading(false)},[]);
  useEffect(()=>{void load()},[load]);
  const filtered=useMemo(()=>items.filter(row=>`${row.post.title} ${row.post.authorName}`.toLowerCase().includes(query.toLowerCase())&&(!categoryFilter||row.post.categoryId===categoryFilter)),[items,query,categoryFilter]);
  async function create(form:HTMLFormElement){setError("");const response=await fetch("/api/admin/posts",{method:"POST",body:new FormData(form)}),data=await response.json().catch(()=>null)as{message?:string}|null;if(response.ok){setCreating(false);setSuccess(data?.message||"Article créé.");await load()}else setError(data?.message||"Création impossible.")}
  async function save(){if(!editing)return;setError("");const response=await fetch(`/api/admin/posts/${editing.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(editing)}),data=await response.json().catch(()=>null)as{message?:string}|null;if(response.ok){setEditing(null);setSuccess(data?.message||"Article modifié.");await load()}else setError(data?.message||"Modification impossible.")}
  async function remove(){if(!pendingDelete)return;const response=await fetch(`/api/admin/posts/${pendingDelete.post.id}`,{method:"DELETE"}),data=await response.json().catch(()=>null)as{message?:string}|null;if(response.ok){setPendingDelete(null);setSuccess(data?.message||"Article supprimé.");await load()}else setError(data?.message||"Suppression impossible.")}
  const category=(id:string|null)=>categories.find(item=>item.id===id);

  return <div className="mx-auto max-w-7xl">
    <SiblingPagination total={filtered.length} pageSize={8} containerSelector=":scope > section.mt-8 > div.mt-6.space-y-3"/>
    <header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-700">Journal</p><h1 className="mt-2 text-3xl font-black">Blog</h1><p className="mt-2 text-slate-500">Créez, classez et publiez les conseils destinés aux parents.</p></div><div className="flex flex-wrap gap-3"><Link href="/admin/blog/categories" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border bg-white px-5 font-black text-slate-700"><Tags size={18}/> Gérer les catégories</Link><button onClick={()=>setCreating(true)} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-slate-900 px-6 font-bold text-white"><Plus size={18}/> Nouvel article</button></div></header>
    <section className="mt-8 rounded-[1.75rem] border bg-white p-6 shadow-sm">
      <div className="grid gap-3 md:grid-cols-[1fr_280px_auto]"><label className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Rechercher un titre ou un auteur…" className="min-h-12 w-full rounded-xl border pl-11 pr-4 outline-none focus:border-emerald-500"/></label><AdminSelect label="Catégorie" value={categoryFilter} options={[{value:"",label:"Toutes les catégories"},...categories.map(item=>({value:item.id,label:`${item.badge} ${item.name}`}))]} onChange={setCategoryFilter}/><button onClick={()=>void load()} aria-label="Actualiser" className="grid size-12 place-items-center rounded-xl border"><RefreshCw size={18}/></button></div>
      {error&&<p className="mt-4 rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p>}
      <div className="mt-6 space-y-3">{loading?<div className="grid h-48 place-items-center"><LoaderCircle className="animate-spin"/></div>:filtered.length===0?<Empty create={()=>setCreating(true)}/>:filtered.map(row=>{const open=expanded===row.post.id,theme=category(row.post.categoryId);return <article key={row.post.id} className="overflow-hidden rounded-2xl border transition hover:shadow-md"><div className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center"><div className="relative h-28 w-full shrink-0 overflow-hidden rounded-xl bg-slate-100 sm:w-40">{row.cover?<Image unoptimized fill src={`/media/${row.cover.path}`} alt={row.cover.alt||row.post.title} className="object-cover"/>:<span className="grid size-full place-items-center text-slate-400"><FileText/></span>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-black">{row.post.title}</h2>{theme&&<span className="rounded-full px-2.5 py-1 text-[10px] font-black" style={{backgroundColor:`${theme.color}20`,color:theme.color}}>{theme.badge} {theme.name}</span>}{row.post.featured&&<span className="inline-flex items-center gap-1 rounded-full bg-amber-50 px-2 py-1 text-[10px] font-black text-amber-700"><Star size={11}/> À LA UNE</span>}<span className={`rounded-full px-2 py-1 text-[10px] font-black ${row.post.published?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{row.post.published?"PUBLIÉ":"BROUILLON"}</span></div><p className="mt-2 line-clamp-1 text-sm text-slate-500">{row.post.excerpt}</p><p className="mt-2 text-xs text-slate-400">Par {row.post.authorName} · Mis à jour le {date(row.post.updatedAt)}</p></div><div className="flex gap-2"><Link href={`/blog/${row.post.slug}`} target="_blank" aria-label="Consulter" className={icon}><Eye size={17}/></Link><button aria-label="Modifier" onClick={()=>setEditing(toEdit(row.post))} className={`${icon} text-amber-600`}><Pencil size={17}/></button><button aria-label="Supprimer" onClick={()=>setPendingDelete(row)} className={`${icon} text-red-600`}><Trash2 size={17}/></button><button aria-label={open?"Masquer le contenu":"Afficher le contenu"} onClick={()=>setExpanded(open?null:row.post.id)} className={icon}>{open?<ChevronUp size={17}/>:<ChevronDown size={17}/>}</button></div></div>{open&&<div className="border-t bg-slate-50 p-5"><p className="text-xs font-black uppercase tracking-wider text-slate-400">Contenu</p><p className="mt-3 whitespace-pre-wrap text-sm leading-relaxed text-slate-600">{row.post.content}</p></div>}</article>})}</div>
    </section>
    {creating&&<CreateDialog categories={categories} close={()=>setCreating(false)} submit={create}/>} {editing&&<EditDialog categories={categories} value={editing} setValue={setEditing} close={()=>setEditing(null)} save={()=>void save()}/>} {pendingDelete&&<DeleteDialog title={pendingDelete.post.title} close={()=>setPendingDelete(null)} confirm={()=>void remove()}/>} {success&&<Success message={success} close={()=>setSuccess("")}/>} 
  </div>;
}

const icon="grid size-10 place-items-center rounded-xl border text-blue-600 transition hover:-translate-y-0.5 hover:bg-slate-50",input="mt-2 min-h-12 w-full rounded-xl border px-4 outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100";
function toEdit(post:Post):Edit{return{id:post.id,language:post.language,title:post.title,excerpt:post.excerpt,content:htmlToMarkdown(post.content),authorName:post.authorName,categoryId:post.categoryId,published:post.published,featured:post.featured}}
function Modal({children,close,width="max-w-3xl"}:{children:React.ReactNode;close:()=>void;width?:string}){return <div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/70 p-4 backdrop-blur-md" onMouseDown={close}><div onMouseDown={event=>event.stopPropagation()} className={`max-h-[92vh] w-full overflow-auto rounded-[1.75rem] bg-white shadow-2xl ${width}`}>{children}</div></div>}
function ThemeSelect({categories,value,onChange,name}:{categories:Category[];value:string;onChange?:(value:string)=>void;name?:string}){return <div><input type="hidden" name={name} value={value}/><AdminSelect label="Catégorie de l’article" value={value} options={[{value:"",label:"Sans catégorie"},...categories.map(item=>({value:item.id,label:`${item.badge} ${item.name}`}))]} onChange={onChange||(()=>undefined)}/>{categories.length===0&&<p className="mt-2 text-xs text-amber-700">Créez d’abord une catégorie depuis « Gérer les catégories ».</p>}</div>}
function CreateDialog({categories,close,submit}:{categories:Category[];close:()=>void;submit:(form:HTMLFormElement)=>Promise<void>}){const[content,setContent]=useState(""),[categoryId,setCategoryId]=useState("");return <Modal close={close}><form onSubmit={event=>{event.preventDefault();void submit(event.currentTarget)}}><Head title="Nouvel article" close={close}/><div className="grid gap-5 p-6"><div className="grid gap-5 sm:grid-cols-[180px_1fr]"><Field label="Langue"><select name="language" className={input} defaultValue="FR"><option value="FR">🇫🇷 Français</option><option value="EN">🇬🇧 Anglais</option></select></Field><Field label="Titre"><input name="title" className={input} required minLength={2} maxLength={150}/></Field></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Auteur"><input name="authorName" className={input} defaultValue="Le Petit Crayon" required minLength={2} maxLength={100}/></Field><Field label="Couverture"><input name="cover" type="file" accept="image/*" className={`${input} py-1`}/></Field></div><ThemeSelect categories={categories} name="categoryId" value={categoryId} onChange={setCategoryId}/><Field label="Résumé"><textarea name="excerpt" className={`${input} min-h-24 py-3`} required minLength={10} maxLength={300}/></Field><MarkdownHelp/><MarkdownEditor name="content" value={content} onChange={setContent}/><Options/><button className="min-h-12 rounded-xl bg-slate-900 font-bold text-white">Créer l’article</button></div></form></Modal>}
function EditDialog({categories,value,setValue,close,save}:{categories:Category[];value:Edit;setValue:(value:Edit)=>void;close:()=>void;save:()=>void}){return <Modal close={close}><Head title="Modifier l’article" close={close}/><div className="grid gap-5 p-6"><div className="grid gap-5 sm:grid-cols-[180px_1fr]"><Field label="Langue"><select className={input} value={value.language} onChange={e=>setValue({...value,language:e.target.value as "FR"|"EN"})}><option value="FR">🇫🇷 Français</option><option value="EN">🇬🇧 Anglais</option></select></Field><Field label="Titre"><input className={input} value={value.title} required minLength={3} maxLength={180} onChange={e=>setValue({...value,title:e.target.value})}/></Field></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Auteur"><input className={input} value={value.authorName} required minLength={2} maxLength={100} onChange={e=>setValue({...value,authorName:e.target.value})}/></Field><ThemeSelect categories={categories} value={value.categoryId||""} onChange={categoryId=>setValue({...value,categoryId:categoryId||null})}/></div><Field label="Résumé"><textarea className={`${input} min-h-24 py-3`} value={value.excerpt} required minLength={10} maxLength={400} onChange={e=>setValue({...value,excerpt:e.target.value})}/></Field><MarkdownHelp/><MarkdownEditor value={value.content} onChange={content=>setValue({...value,content})}/><label className="flex gap-3"><input type="checkbox" checked={value.published} onChange={e=>setValue({...value,published:e.target.checked})}/> Publié</label><label className="flex gap-3"><input type="checkbox" checked={value.featured} onChange={e=>setValue({...value,featured:e.target.checked})}/> À la une</label><button onClick={save} className="min-h-12 rounded-xl bg-emerald-700 font-bold text-white">Enregistrer</button></div></Modal>}
function MarkdownHelp(){return <div className="rounded-xl border border-emerald-100 bg-emerald-50 p-4 text-xs leading-6 text-slate-600"><strong className="text-emerald-800">Markdown accepté :</strong> <code># Titre</code> · <code>**gras**</code> · <code>*italique*</code> · <code>- liste</code> · <code>[lien](https://…)</code></div>}
function Options(){return <div className="flex flex-wrap gap-6 rounded-xl bg-slate-50 p-4"><label className="flex gap-2 text-sm font-bold"><input type="checkbox" name="published"/> Publier immédiatement</label><label className="flex gap-2 text-sm font-bold"><input type="checkbox" name="featured"/> Mettre à la une</label></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <AdminFormField label={label}>{children}</AdminFormField>}
function Head({title,close}:{title:string;close:()=>void}){return <div className="flex items-center justify-between border-b p-6"><h2 className="text-2xl font-black">{title}</h2><button type="button" aria-label="Fermer" onClick={close} className="grid size-10 place-items-center rounded-xl bg-slate-100"><X/></button></div>}
function DeleteDialog({title,close,confirm}:{title:string;close:()=>void;confirm:()=>void}){return <Modal close={close} width="max-w-md"><div className="p-8 text-center"><span className="mx-auto grid size-16 place-items-center rounded-full bg-red-100 text-red-600"><AlertTriangle size={30}/></span><h2 className="mt-5 text-2xl font-black">Supprimer cet article ?</h2><p className="mt-3 text-slate-500"><strong>{title}</strong> sera définitivement supprimé.</p><div className="mt-7 grid grid-cols-2 gap-3"><button onClick={close} className="rounded-xl border py-3 font-bold">Annuler</button><button onClick={confirm} className="rounded-xl bg-red-600 py-3 font-bold text-white">Supprimer</button></div></div></Modal>}
function Success({message,close}:{message:string;close:()=>void}){return <Modal close={close} width="max-w-sm"><div className="p-8 text-center"><CheckCircle2 size={54} className="mx-auto text-emerald-600"/><h2 className="mt-5 text-2xl font-black">Opération réussie</h2><p className="mt-3 text-slate-500">{message}</p><button onClick={close} className="mt-7 w-full rounded-xl bg-slate-900 py-3 font-bold text-white">Terminer</button></div></Modal>}
function Empty({create}:{create:()=>void}){return <div className="grid min-h-64 place-items-center rounded-2xl border border-dashed bg-slate-50 text-center"><div><FileText className="mx-auto text-slate-400"/><h2 className="mt-3 font-black">Aucun article</h2><button onClick={create} className="mt-4 rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white">Créer le premier article</button></div></div>}
function date(value:string){return new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium"}).format(new Date(value))}
