"use client";

import Image from "next/image";
import Link from "next/link";
import { AlertTriangle, BookOpen, ChevronDown, ChevronUp, Eye, Languages, LoaderCircle, Pencil, RefreshCw, Search, Trash2, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AdminSelect } from "./admin-select";
import { BookGallery } from "./book-management-list";

type Book={id:string;slug:string;language:"FR"|"EN";title:string;shortDescription:string;description:string;ageMin:number|null;ageMax:number|null;pageCount:number|null;published:boolean;createdAt:string;updatedAt:string};
type Row={book:Book;cover:{path:string;alt:string|null}|null};

export function BookCatalogList(){
  const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[language,setLanguage]=useState(""),[expanded,setExpanded]=useState<string|null>(null),[pendingDelete,setPendingDelete]=useState<Book|null>(null),[success,setSuccess]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch("/api/admin/books",{cache:"no-store"}),data=await response.json().catch(()=>null)as{items?:Row[];message?:string}|null;if(!response.ok)throw new Error(data?.message||"Chargement impossible.");setRows(data?.items||[])}catch(cause){setError(cause instanceof Error?cause.message:"Chargement impossible.")}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const items=useMemo(()=>{const q=query.trim().toLocaleLowerCase("fr");return rows.filter(({book})=>(!language||book.language===language)&&(!q||`${book.title} ${book.shortDescription}`.toLocaleLowerCase("fr").includes(q)))},[rows,query,language]);
  async function remove(){if(!pendingDelete)return;const response=await fetch(`/api/admin/books/${pendingDelete.id}`,{method:"DELETE"}),data=await response.json().catch(()=>null)as{message?:string}|null;if(!response.ok){setError(data?.message||"Suppression impossible.");setPendingDelete(null);return}setSuccess(data?.message||"Livre supprimé.");setPendingDelete(null);await load()}
  const filtered=Boolean(query||language);

  return <section className="mx-auto mt-8 max-w-6xl rounded-[1.75rem] border border-slate-200 bg-white p-5 shadow-sm transition-colors dark:border-white/10 dark:bg-white/[.035] md:p-7">
    <header className="flex items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700 dark:text-emerald-400">Catalogue</p><h2 className="mt-1 text-2xl font-black text-slate-950 dark:text-white">Liste des livres</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{items.length} livre{items.length!==1?"s":""} affiché{items.length!==1?"s":""}</p></div><button aria-label="Actualiser" onClick={()=>void load()} className="grid size-12 place-items-center rounded-2xl border border-slate-200 bg-white text-slate-500 shadow-sm transition hover:-translate-y-0.5 hover:border-emerald-300 hover:text-emerald-700 hover:shadow-md dark:border-white/10 dark:bg-white/5 dark:text-slate-300 dark:hover:border-emerald-500/40 dark:hover:bg-emerald-500/10 dark:hover:text-emerald-300"><RefreshCw size={19}/></button></header>

    <section className="relative mt-6 overflow-visible rounded-[1.5rem] border border-emerald-100 bg-gradient-to-br from-emerald-50/70 via-white to-amber-50/40 p-4 shadow-[0_16px_45px_-35px_rgba(15,118,110,.6)] transition-colors dark:border-emerald-500/20 dark:bg-none dark:bg-[#111b1a] dark:shadow-[0_18px_50px_-35px_rgba(16,185,129,.35)] md:p-5">
      <div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-emerald-700 dark:text-emerald-400">Recherche intelligente</p><h3 className="mt-1 text-lg font-black text-slate-950 dark:text-white">Trouver rapidement un livre</h3></div>{filtered&&<button type="button" onClick={()=>{setQuery("");setLanguage("")}} className="rounded-full border border-emerald-200 bg-white px-4 py-2 text-xs font-black text-emerald-700 shadow-sm transition hover:bg-emerald-700 hover:text-white dark:border-emerald-500/30 dark:bg-emerald-500/10 dark:text-emerald-300 dark:hover:bg-emerald-500 dark:hover:text-slate-950">Réinitialiser les filtres</button>}</div>
      <div className="grid gap-3 lg:grid-cols-[minmax(280px,1fr)_310px]">
        <label className="group relative block"><span className="absolute left-4 top-1/2 z-10 grid size-9 -translate-y-1/2 place-items-center rounded-xl bg-emerald-50 text-emerald-700 transition group-focus-within:bg-emerald-700 group-focus-within:text-white dark:bg-emerald-500/10 dark:text-emerald-300 dark:group-focus-within:bg-emerald-500 dark:group-focus-within:text-slate-950"><Search size={17}/></span><span className="sr-only">Rechercher un livre</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Titre, résumé ou mot-clé…" className="min-h-16 w-full rounded-2xl border border-slate-200 bg-white pl-16 pr-12 font-bold text-slate-800 shadow-sm outline-none transition placeholder:font-semibold placeholder:text-slate-400 hover:border-emerald-300 hover:shadow-md focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100 dark:border-white/10 dark:bg-slate-950/70 dark:text-white dark:placeholder:text-slate-500 dark:hover:border-emerald-500/40 dark:focus:border-emerald-500 dark:focus:ring-emerald-500/15"/>{query&&<button type="button" aria-label="Effacer la recherche" onClick={()=>setQuery("")} className="absolute right-4 top-1/2 grid size-8 -translate-y-1/2 place-items-center rounded-full bg-slate-100 text-slate-500 hover:bg-slate-200 dark:bg-white/10 dark:text-slate-300 dark:hover:bg-white/15"><X size={15}/></button>}</label>
        <AdminSelect label="Langue du livre" icon={<Languages size={18}/>} value={language} options={[{value:"",label:"Toutes les langues"},{value:"FR",label:"🇫🇷 Français"},{value:"EN",label:"🇬🇧 Anglais"}]} onChange={setLanguage}/>
      </div>
      <div className="mt-4 flex flex-wrap items-center gap-2 text-xs font-bold text-slate-500 dark:text-slate-400"><span className="rounded-full bg-white px-3 py-1.5 shadow-sm dark:border dark:border-white/10 dark:bg-white/5"><strong className="text-slate-950 dark:text-white">{items.length}</strong> résultat{items.length!==1?"s":""}</span>{language&&<span className="rounded-full bg-emerald-700 px-3 py-1.5 text-white dark:bg-emerald-500 dark:text-slate-950">{language==="FR"?"🇫🇷 Français":"🇬🇧 Anglais"}</span>}{query&&<span className="max-w-60 truncate rounded-full bg-white px-3 py-1.5 shadow-sm dark:border dark:border-white/10 dark:bg-white/5">Recherche : « {query} »</span>}</div>
    </section>

    {error&&<p className="mt-5 rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p>}{success&&<p className="mt-5 rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{success}</p>}
    <div className="mt-6 space-y-4">{loading?<div className="grid min-h-44 place-items-center"><LoaderCircle className="animate-spin text-emerald-700"/></div>:items.length===0?<Empty/>:items.map(row=><BookRow key={row.book.id} row={row} open={expanded===row.book.id} toggle={()=>setExpanded(expanded===row.book.id?null:row.book.id)} remove={()=>setPendingDelete(row.book)}/>)}</div>
    {pendingDelete&&<Modal close={()=>setPendingDelete(null)}><div className="p-7 text-center"><AlertTriangle className="mx-auto text-red-600" size={42}/><h2 className="mt-4 text-2xl font-black">Supprimer ce livre ?</h2><p className="mt-3 text-slate-500"><strong>{pendingDelete.title}</strong> et ses médias seront supprimés.</p><div className="mt-7 grid grid-cols-2 gap-3"><button onClick={()=>setPendingDelete(null)} className="rounded-xl border py-3 font-bold">Annuler</button><button onClick={()=>void remove()} className="rounded-xl bg-red-600 py-3 font-bold text-white">Supprimer</button></div></div></Modal>}
  </section>;
}

function BookRow({row,open,toggle,remove}:{row:Row;open:boolean;toggle:()=>void;remove:()=>void}){const{book,cover}=row;return <article className="overflow-hidden rounded-[1.4rem] border bg-white transition hover:-translate-y-0.5 hover:border-emerald-200 hover:shadow-lg"><div className="flex flex-col gap-5 p-4 sm:flex-row sm:items-center"><div className="relative h-52 w-full shrink-0 overflow-hidden rounded-2xl border bg-[linear-gradient(135deg,#f8fafc_25%,#fff_25%,#fff_50%,#f8fafc_50%,#f8fafc_75%,#fff_75%)] bg-[length:16px_16px] shadow-inner sm:h-40 sm:w-36">{cover?<Image unoptimized fill sizes="144px" src={`/media/${cover.path}`} alt={cover.alt||book.title} className="object-contain p-2"/>:<span className="grid size-full place-items-center text-slate-400"><BookOpen size={30}/></span>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate text-lg font-black text-slate-950">{book.title}</h3><Status published={book.published}/><Language language={book.language}/></div><p className="mt-3 line-clamp-2 text-sm leading-relaxed text-slate-500">{book.shortDescription}</p><p className="mt-3 text-xs font-semibold text-slate-400">Créé le {date(book.createdAt)} · Mis à jour le {date(book.updatedAt)}</p><p className="mt-2 text-sm font-bold text-slate-600">{book.ageMin??0}–{book.ageMax??0} ans · {book.pageCount??0} pages</p></div><div className="flex shrink-0 items-center gap-2"><Link aria-label="Consulter" target="_blank" href={`${book.language==="EN"?"/en/books":"/livres"}/${book.slug}`} className={action}><Eye size={17}/></Link><Link aria-label="Modifier" href={`/admin/livres/${book.id}/modifier`} className={`${action} text-amber-600`}><Pencil size={17}/></Link><button aria-label="Supprimer" onClick={remove} className={`${action} text-red-600`}><Trash2 size={17}/></button><button aria-label="Détails" onClick={toggle} className={`${action} text-slate-600`}>{open?<ChevronUp size={18}/>:<ChevronDown size={18}/>}</button></div></div>{open&&<div className="border-t bg-slate-50/70 px-5 py-5"><p className="text-xs font-black uppercase tracking-wider text-slate-400">Description</p><p className="mt-2 text-sm leading-relaxed text-slate-600">{book.description}</p><BookGallery bookId={book.id}/></div>}</article>}
const action="grid size-10 place-items-center rounded-xl border text-blue-600 transition hover:-translate-y-0.5 hover:bg-slate-50";
function Status({published}:{published:boolean}){return <span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${published?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{published?"Publié":"Brouillon"}</span>}
function Language({language}:{language:"FR"|"EN"}){return <span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ring-1 ${language==="EN"?"bg-blue-50 text-blue-700 ring-blue-100":"bg-violet-50 text-violet-700 ring-violet-100"}`}>{language==="EN"?"🇬🇧 Anglais":"🇫🇷 Français"}</span>}
function Empty(){return <div className="grid min-h-48 place-items-center rounded-2xl border border-dashed bg-slate-50 text-center"><div><BookOpen className="mx-auto text-slate-400"/><p className="mt-3 font-bold">Aucun livre ne correspond aux filtres</p></div></div>}
function Modal({children,close}:{children:React.ReactNode;close:()=>void}){return <div className="fixed inset-0 z-[130] grid place-items-center bg-slate-950/70 p-4" onMouseDown={close}><div onMouseDown={event=>event.stopPropagation()} className="relative w-full max-w-md rounded-[1.75rem] bg-white shadow-2xl"><button aria-label="Fermer" onClick={close} className="absolute right-4 top-4 grid size-10 place-items-center rounded-xl bg-slate-100"><X size={18}/></button>{children}</div></div>}
function date(value:string){return new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium"}).format(new Date(value))}
