"use client";
import Link from "next/link";
import { CodeCreationDialog } from "./code-creation-dialog";

import { useCallback, useEffect, useState } from "react";
import { Check, CheckCircle2, Clipboard, Instagram, KeyRound, LoaderCircle, Plus, Power, PowerOff, RefreshCw, Trash2, X } from "lucide-react";
import { INSTAGRAM_URL } from "@/lib/site-config";
import { SiblingPagination } from "@/components/client-pagination";

type CodeRow = { bookTitle: string | null; code: { bookId: string | null; id: string; codeHint: string; instagramHandle: string | null; status: "ACTIVE" | "REDEEMED" | "DISABLED"; accessDurationMinutes: number; createdAt: string; expiresAt: string; redeemedAt: string | null }; downloads: number };

export function ClubCodeManager() {
  const [items, setItems] = useState<CodeRow[]>([]), [loading, setLoading] = useState(true), [creating, setCreating] = useState(false);
  const [generated, setGenerated] = useState(""), [copied, setCopied] = useState(false), [error, setError] = useState("");
  const [pendingDelete, setPendingDelete] = useState<CodeRow | null>(null), [pendingToggle, setPendingToggle] = useState<CodeRow | null>(null), [success, setSuccess] = useState("");
  const load = useCallback(async () => { setLoading(true); const response = await fetch("/api/admin/club-codes", { cache: "no-store" }); if (response.ok) setItems(((await response.json()) as { items: CodeRow[] }).items); setLoading(false); }, []);
  useEffect(() => { void load(); }, [load]);


  async function toggle() { if (!pendingToggle) return; const status = pendingToggle.code.status === "DISABLED" ? "ACTIVE" : "DISABLED"; const response = await fetch(`/api/admin/club-codes/${pendingToggle.code.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); const data = await response.json().catch(() => null) as { message?: string } | null; if (response.ok) { setPendingToggle(null); setSuccess(data?.message || "Code modifié."); await load(); } else { setPendingToggle(null); setError(data?.message || "Modification impossible."); } }
  async function remove() { if (!pendingDelete) return; const response = await fetch(`/api/admin/club-codes/${pendingDelete.code.id}`, { method: "DELETE" }); if (response.ok) { setPendingDelete(null); setSuccess("Code supprimé avec succès."); await load(); } }
  async function copy() { await navigator.clipboard.writeText(generated); setCopied(true); window.setTimeout(() => setCopied(false), 1800); }

  return <div className="mx-auto max-w-6xl"><SiblingPagination total={items.length} pageSize={10} containerSelector=":scope > section.mt-8 > div.mt-6.space-y-3"/><header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-700">Club Instagram</p><h1 className="mt-2 text-3xl font-black">Codes d’accès</h1><p className="mt-2 max-w-2xl text-slate-500">Après vérification auprès du parent, générez un code Club Instagram ou un code bonus lié à un livre. Chaque code est utilisable une seule fois.</p></div><button onClick={() => setCreating(true)} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-slate-900 px-6 font-black text-white"><Plus size={18}/> Générer un code</button></header>
    {error && <p className="mt-5 rounded-xl bg-red-50 p-4 font-bold text-red-700">{error}</p>}
    <section className="mt-8 rounded-[1.75rem] border bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Pass créés</h2><p className="mt-1 text-sm text-slate-500">{items.length} code{items.length > 1 ? "s" : ""}</p></div><button aria-label="Actualiser" onClick={() => void load()} className="grid size-11 place-items-center rounded-xl border"><RefreshCw size={18}/></button></div>
      <div className="mt-6 space-y-3">{loading ? <div className="grid h-40 place-items-center"><LoaderCircle className="animate-spin"/></div> : items.length === 0 ? <div className="grid min-h-56 place-items-center rounded-2xl border border-dashed bg-slate-50 text-center"><div><KeyRound className="mx-auto text-slate-400" size={34}/><h2 className="mt-3 font-black">Aucun code créé</h2><p className="mt-1 text-sm text-slate-500">Générez votre premier Pass Instagram.</p></div></div> : items.map(row => <article key={row.code.id} className="flex flex-col gap-4 rounded-2xl border p-4 md:flex-row md:items-center"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><KeyRound/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><code className="font-black text-slate-900">{row.code.codeHint}</code><Status value={row.code.status}/>{row.code.bookId ? <Link href={`/admin/livres/${row.code.bookId}/modifier`} className="text-xs font-bold text-emerald-700 underline decoration-emerald-300 underline-offset-4 hover:text-emerald-600 dark:text-emerald-300">Bonus : {row.bookTitle || "Livre associé"} ↗</Link> : <span className="text-xs font-bold text-emerald-700 dark:text-emerald-300">Club Instagram</span>}</div><p className="mt-2 text-xs text-slate-500">{row.code.instagramHandle ? `Référence : ${row.code.instagramHandle} · ` : ""}Créé le {date(row.code.createdAt)} · expire le {date(row.code.expiresAt)} · {row.downloads} téléchargement{row.downloads > 1 ? "s" : ""}</p></div><div className="flex gap-2">{row.code.status !== "REDEEMED" && <button aria-label={row.code.status === "DISABLED" ? "Réactiver le code" : "Désactiver le code"} onClick={() => setPendingToggle(row)} className={`grid size-10 place-items-center rounded-xl border transition ${row.code.status === "DISABLED" ? "border-emerald-200 bg-emerald-50 text-emerald-700 hover:bg-emerald-100" : "border-red-200 bg-red-50 text-red-600 hover:bg-red-100"}`}>{row.code.status === "DISABLED" ? <Power size={17}/> : <PowerOff size={17}/>}</button>}<button aria-label="Supprimer" onClick={() => setPendingDelete(row)} className="grid size-10 place-items-center rounded-xl border text-red-600"><Trash2 size={17}/></button></div></article>)}</div>
    </section>
    {creating && <CodeCreationDialog close={() => setCreating(false)} created={code => { setCreating(false); setGenerated(code); setCopied(false); void load(); }}/>}
    {generated && <Modal close={() => setGenerated("")}><div className="relative p-8 text-center"><button aria-label="Fermer" onClick={() => setGenerated("")} className="absolute right-5 top-5 grid size-11 place-items-center rounded-full border border-slate-200 bg-white text-slate-500 shadow-sm transition hover:rotate-90 hover:border-slate-300 hover:bg-slate-100 hover:text-slate-900"><X size={20}/></button><CheckCircle2 className="mx-auto text-emerald-600" size={54}/><h2 className="mt-4 text-2xl font-black">Code prêt à envoyer</h2><p className="mt-2 text-sm text-slate-500">Copiez-le maintenant : il ne sera ensuite affiché que partiellement.</p><code className="mt-6 block rounded-2xl bg-slate-950 px-4 py-5 text-xl font-black tracking-wider text-white">{generated}</code><button onClick={() => void copy()} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-700 px-5 py-3 font-black text-white">{copied ? <Check size={18}/> : <Clipboard size={18}/>} {copied ? "Copié !" : "Copier le code"}</button><a href={INSTAGRAM_URL} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-2 text-sm font-bold text-emerald-700"><Instagram size={17}/> Ouvrir Instagram</a></div></Modal>}
    {pendingToggle && <Modal close={() => setPendingToggle(null)}><div className="p-8 text-center"><span className={`mx-auto grid size-16 place-items-center rounded-full ${pendingToggle.code.status === "DISABLED" ? "bg-emerald-100 text-emerald-700" : "bg-red-100 text-red-600"}`}>{pendingToggle.code.status === "DISABLED" ? <Power size={30}/> : <PowerOff size={30}/>}</span><h2 className="mt-5 text-2xl font-black">{pendingToggle.code.status === "DISABLED" ? "Réactiver ce code ?" : "Désactiver ce code ?"}</h2><p className="mt-3 leading-relaxed text-slate-500">{pendingToggle.code.status === "DISABLED" ? "Le code pourra de nouveau être utilisé jusqu’à sa date d’expiration." : "Le code ne pourra plus être utilisé tant que vous ne l’aurez pas réactivé."}</p><div className="mt-7 grid grid-cols-2 gap-3"><button onClick={() => setPendingToggle(null)} className="rounded-xl border py-3 font-bold text-slate-600">Annuler</button><button onClick={() => void toggle()} className={`rounded-xl py-3 font-bold text-white ${pendingToggle.code.status === "DISABLED" ? "bg-emerald-700" : "bg-red-600"}`}>{pendingToggle.code.status === "DISABLED" ? "Réactiver" : "Désactiver"}</button></div></div></Modal>}
    {pendingDelete && <Modal close={() => setPendingDelete(null)}><div className="p-8 text-center"><Trash2 className="mx-auto text-red-600" size={45}/><h2 className="mt-4 text-2xl font-black">Supprimer ce code ?</h2><p className="mt-3 text-slate-500">L’accès déjà activé sera également révoqué.</p><div className="mt-7 grid grid-cols-2 gap-3"><button onClick={() => setPendingDelete(null)} className="rounded-xl border py-3 font-bold">Annuler</button><button onClick={() => void remove()} className="rounded-xl bg-red-600 py-3 font-bold text-white">Supprimer</button></div></div></Modal>}
    {success && <Modal close={() => setSuccess("")}><div className="p-8 text-center"><CheckCircle2 className="mx-auto text-emerald-600" size={54}/><h2 className="mt-4 text-2xl font-black">Opération réussie</h2><p className="mt-3 text-slate-500">{success}</p><button onClick={() => setSuccess("")} className="mt-6 w-full rounded-xl bg-slate-900 py-3 font-bold text-white">Terminer</button></div></Modal>}
  </div>;
}

function Status({ value }: { value: CodeRow["code"]["status"] }) { const styles = value === "ACTIVE" ? "bg-emerald-50 text-emerald-700" : value === "REDEEMED" ? "bg-blue-50 text-blue-700" : "bg-slate-100 text-slate-500"; return <span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${styles}`}>{value === "ACTIVE" ? "ACTIF" : value === "REDEEMED" ? "UTILISÉ" : "DÉSACTIVÉ"}</span>; }
function Modal({ children, close }: { children: React.ReactNode; close: () => void }) { return <div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/70 p-4 backdrop-blur-md" onMouseDown={close}><div role="dialog" aria-modal="true" onMouseDown={event => event.stopPropagation()} className="max-h-[92vh] w-full max-w-lg overflow-auto rounded-[1.75rem] bg-white shadow-2xl">{children}</div></div>; }

function date(value: string) { return new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium" }).format(new Date(value)); }
