import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import * as schema from "./schema";
import path from "node:path";
import fs from "node:fs";
const databasePath=path.resolve(/* turbopackIgnore: true */ process.env.DATABASE_PATH ?? "./data/database/site.db");
fs.mkdirSync(path.dirname(databasePath),{recursive:true});
const sqlite=new Database(databasePath);
sqlite.pragma("journal_mode = WAL");
sqlite.pragma("synchronous = NORMAL");
sqlite.pragma("foreign_keys = ON");
sqlite.pragma("busy_timeout = 5000");
sqlite.pragma("temp_store = MEMORY");
sqlite.pragma("cache_size = -20000");
sqlite.pragma("wal_autocheckpoint = 1000");
export const db=drizzle(sqlite,{schema});
export {sqlite,databasePath};
