"use client";

import { Check, ChevronDown, Search, SlidersHorizontal, Tags, WalletCards, ArrowDownUp, RotateCcw } from "lucide-react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import type {Locale} from "@/lib/i18n";

type Option={value:string;label:string};
type Props={query?:string;category?:string;pricing?:string;sort?:string;categories:Array<{slug:string;name:string}>;locale?:Locale};

export function BookFilters({query,category,pricing,sort="newest",categories,locale="fr"}:Props){const en=locale==="en",pathname=usePathname(),hasFilters=Boolean(query?.trim()||category||pricing||sort!=="newest");return <form className="relative z-20 mb-6 rounded-[1.5rem] border bg-card/95 p-4 shadow-[0_18px_55px_-38px_rgba(15,23,42,.45)] backdrop-blur"><div className="mb-3 flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-primary/10 text-primary"><SlidersHorizontal size={18}/></span><div><p className="font-display font-black text-foreground">{en?"Find your next book":"Trouver votre prochain livre"}</p><p className="text-[11px] font-semibold text-foreground/55">{en?"Refine the collection in a few clicks":"Affinez le catalogue en quelques clics"}</p></div></div>{hasFilters&&<Link href={pathname} scroll={false} className="inline-flex min-h-9 items-center gap-2 rounded-xl border bg-background px-3 text-xs font-black text-foreground/65 transition hover:border-primary/40 hover:text-primary"><RotateCcw size={14}/><span className="hidden sm:inline">{en?"Reset":"Réinitialiser"}</span></Link>}</div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-[minmax(220px,1.35fr)_minmax(255px,1.2fr)_minmax(205px,1fr)_minmax(175px,.85fr)_auto]"><label className="group relative"><span className="sr-only">{en?"Search for a book":"Rechercher un livre"}</span><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-foreground/35 transition group-focus-within:text-primary" size={18}/><input name="q" defaultValue={query} placeholder={en?"Search for a book…":"Rechercher un livre…"} className="focus-ring min-h-12 w-full rounded-2xl border bg-background/70 pl-11 pr-4 font-semibold text-foreground placeholder:text-foreground/40"/></label><FilterSelect name="category" label={en?"Category":"Catégorie"} icon={<Tags size={16}/>} value={category||""} options={[{value:"",label:en?"All categories":"Toutes les catégories"},...categories.map(item=>({value:item.slug,label:item.name}))]}/><FilterSelect name="pricing" label={en?"Price":"Tarif"} icon={<WalletCards size={16}/>} value={pricing||""} options={[{value:"",label:en?"Free and paid":"Gratuits et payants"},{value:"FREE",label:en?"Free books":"Livres gratuits"},{value:"PAID",label:en?"Paid books":"Livres payants"}]}/><FilterSelect name="sort" label={en?"Sort":"Classement"} icon={<ArrowDownUp size={16}/>} value={sort} options={[{value:"newest",label:en?"Newest":"Plus récents"},{value:"oldest",label:en?"Oldest":"Plus anciens"}]}/><button className="min-h-12 rounded-2xl bg-primary px-6 font-black text-white shadow-lg shadow-primary/20 transition hover:-translate-y-0.5 hover:brightness-110 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-primary/25 md:col-span-2 xl:col-span-1">{en?"Apply":"Appliquer"}</button></div></form>}

function FilterSelect({name,label,icon,value:initial,options}:{name:string;label:string;icon:React.ReactNode;value:string;options:Option[]}){const[value,setValue]=useState(initial),[open,setOpen]=useState(false),root=useRef<HTMLDivElement>(null),selected=options.find(option=>option.value===value)??options[0];useEffect(()=>{const close=(event:MouseEvent)=>{if(!root.current?.contains(event.target as Node))setOpen(false)},escape=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false)};document.addEventListener("mousedown",close);document.addEventListener("keydown",escape);return()=>{document.removeEventListener("mousedown",close);document.removeEventListener("keydown",escape)}},[]);return <div ref={root} className="relative"><input type="hidden" name={name} value={value}/><button type="button" aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(current=>!current)} className={`flex min-h-12 w-full items-center gap-3 rounded-2xl border bg-background/70 px-4 text-left transition ${open?"border-primary ring-4 ring-primary/10":"hover:border-primary/40"}`}><span className="text-primary">{icon}</span><span className="min-w-0 flex-1"><span className="block text-[10px] font-black uppercase tracking-[.14em] text-foreground/45">{label}</span><span className="block truncate text-sm font-bold text-foreground">{selected.label}</span></span><ChevronDown size={17} className={`shrink-0 text-foreground/45 transition duration-200 ${open?"rotate-180 text-primary":""}`}/></button>{open&&<div role="listbox" className="absolute left-0 right-0 top-[calc(100%+.55rem)] z-50 max-h-[min(24rem,60vh)] overflow-y-auto overscroll-contain rounded-2xl border bg-card p-2 shadow-2xl shadow-slate-950/15"><p className="sticky top-0 z-10 bg-card px-3 pb-2 pt-1 text-[10px] font-black uppercase tracking-[.14em] text-foreground/40">{label}</p>{options.map(option=><button key={option.value||"all"} type="button" role="option" aria-selected={option.value===value} onClick={()=>{setValue(option.value);setOpen(false)}} className={`flex min-h-11 w-full items-center justify-between gap-3 rounded-xl px-3 text-left text-sm font-bold transition ${option.value===value?"bg-primary text-white":"text-foreground hover:bg-primary/10 hover:text-primary"}`}><span>{option.label}</span>{option.value===value&&<Check size={17}/>}</button>)}</div>}</div>}
