"use client";
import Image from "next/image";
import Link from "next/link";
import {ArrowRight,BookOpen,Heart,Sparkles,Users,X} from "lucide-react";
import {useEffect,useRef,useState} from "react";
import {createPortal} from "react-dom";
import {MarkdownContent} from "@/components/markdown-content";

type Character={name:string;slug:string;color:string;shortDescription:string;biography:string|null;ageLabel:string|null;species:string|null;personality:string|null;hobbies:string|null;motto:string|null;portraitPath:string|null};
export function CharacterFilter({options,selected,path,query,locale="fr"}:{options:Character[];selected?:string;path:string;query:{q?:string;category?:string;sort?:string};locale?:"fr"|"en"}){
 const[opened,setOpened]=useState<Character|null>(null);if(!options.length)return null;
 const hrefFor=(character?:string)=>{const p=new URLSearchParams();if(query.q)p.set("q",query.q);if(query.category)p.set("category",query.category);if(query.sort)p.set("sort",query.sort);if(character)p.set("character",character);return `${path}${p.size?`?${p}`:""}`};
 return <><section aria-label={locale==="en"?"Characters":"Personnages"} className="mb-5 rounded-[1.65rem] border border-emerald-900/10 bg-white/75 p-4 shadow-sm backdrop-blur dark:border-white/10 dark:bg-white/[.045]"><div className="mb-3 flex items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="grid size-9 place-items-center rounded-xl bg-emerald-100 text-emerald-700 dark:bg-emerald-400/15 dark:text-emerald-300"><Users size={17}/></span><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-primary">{locale==="en"?"Meet the cast":"Les héros de la galerie"}</p><h2 className="text-sm font-black">{locale==="en"?"Discover a character":"Découvrir un personnage"}</h2></div></div>{selected&&<Link href={hrefFor()} className="inline-flex min-h-9 items-center gap-1 rounded-full px-2.5 text-xs font-bold text-foreground/55 hover:bg-foreground/5"><X size={13}/>{locale==="en"?"Clear filter":"Effacer le filtre"}</Link>}</div><div className="flex flex-wrap gap-2">{options.map(c=><button type="button" key={c.slug} onClick={()=>setOpened(c)} aria-haspopup="dialog" className={`group inline-flex min-h-11 items-center gap-2.5 rounded-full border px-3.5 text-sm font-extrabold transition hover:-translate-y-0.5 hover:shadow-md ${selected===c.slug?"border-transparent bg-slate-950 text-white shadow-md dark:bg-white dark:text-slate-950":"border-foreground/10 bg-background/75 text-foreground/75 hover:border-primary/35 dark:bg-white/5"}`}>{c.portraitPath?<span className="relative size-7 overflow-hidden rounded-full bg-white/70"><Image fill unoptimized sizes="28px" src={`/media/${c.portraitPath}`} alt="" className="object-cover"/></span>:<span className="size-2.5 rounded-full ring-2 ring-white/70" style={{backgroundColor:c.color}}/>}{c.name}<Sparkles size={13} className="opacity-50 transition group-hover:rotate-12 group-hover:opacity-100"/></button>)}</div></section>{opened&&<Profile character={opened} locale={locale} active={selected===opened.slug} href={hrefFor(opened.slug)} close={()=>setOpened(null)}/>}</>
}
function Profile({character:c,locale,active,href,close}:{character:Character;locale:"fr"|"en";active:boolean;href:string;close:()=>void}){
 const panel=useRef<HTMLDivElement>(null),en=locale==="en";
 const[tab,setTab]=useState<"essential"|"story">("essential");
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;document.body.style.overflow="hidden";panel.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==="Escape")close()};window.addEventListener("keydown",key);return()=>{window.removeEventListener("keydown",key);document.body.style.overflow=overflow;previous?.focus()}},[close]);
 const tabs=[{id:"essential" as const,label:en?"Essentials":"L’essentiel",icon:Sparkles},{id:"story" as const,label:en?"Story & personality":"Histoire & personnalité",icon:BookOpen}];
 return createPortal(<div className="fixed inset-0 z-[150] grid place-items-center bg-slate-950/80 p-2 backdrop-blur-md sm:p-5" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}>
  <div ref={panel} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="profile-title" className="grid max-h-[calc(100dvh-1rem)] w-full max-w-5xl overflow-hidden rounded-[1.75rem] border border-white/10 bg-white shadow-2xl outline-none dark:bg-slate-900 sm:max-h-[calc(100dvh-2.5rem)] md:grid-cols-[minmax(17rem,.78fr)_minmax(0,1.22fr)]">
   <div className="relative h-56 min-h-0 overflow-hidden border-b border-slate-200 md:h-auto md:border-b-0 md:border-r dark:border-white/10" style={{background:`radial-gradient(circle at 50% 45%,${c.color}38,transparent 58%),linear-gradient(145deg,${c.color}22,${c.color}08)`}}>
    {c.portraitPath?<Image fill priority unoptimized sizes="(max-width:768px) 100vw,390px" src={`/media/${c.portraitPath}`} alt={c.name} className="object-contain p-3 sm:p-5"/>:<div className="grid h-full place-items-center"><Heart size={90} strokeWidth={1} style={{color:c.color}}/></div>}
    <span className="absolute bottom-4 left-1/2 -translate-x-1/2 whitespace-nowrap rounded-full bg-white/85 px-3 py-1.5 text-xs font-black text-slate-800 shadow-md backdrop-blur dark:bg-slate-950/75 dark:text-white">{c.species||(en?"Character":"Personnage")}</span>
   </div>
   <div className="flex min-h-0 flex-col">
    <header className="relative shrink-0 px-5 pb-4 pt-5 pr-16 sm:px-6 sm:pb-5 sm:pt-6 sm:pr-20"><p className="text-[10px] font-black uppercase tracking-[.2em] text-primary">{en?"Character profile":"Fiche personnage"}</p><h2 id="profile-title" className="mt-1 break-words font-display text-3xl font-black leading-tight dark:text-white sm:text-4xl">{c.name}</h2><button onClick={close} aria-label={en?"Close":"Fermer"} className="absolute right-4 top-4 grid size-10 place-items-center rounded-full border border-slate-200 bg-white text-slate-600 shadow-sm transition hover:rotate-90 hover:bg-slate-50 dark:border-white/10 dark:bg-white/5 dark:text-white dark:hover:bg-white/10"><X size={19}/></button></header>
    <div role="tablist" aria-label={en?"Character sections":"Sections du personnage"} className="flex shrink-0 gap-2 border-y border-slate-200 px-4 py-3 dark:border-white/10 sm:px-6">{tabs.map(item=><button key={item.id} id={`profile-tab-${item.id}`} role="tab" aria-selected={tab===item.id} aria-controls="profile-panel" type="button" onClick={()=>setTab(item.id)} onKeyDown={event=>{if(event.key==="ArrowLeft"||event.key==="ArrowRight"){event.preventDefault();const next=tab==="essential"?"story":"essential";setTab(next);document.getElementById(`profile-tab-${next}`)?.focus()}}} className={`inline-flex min-h-10 items-center justify-center gap-2 rounded-xl px-3 text-xs font-black transition sm:px-4 sm:text-sm ${tab===item.id?"bg-primary text-white shadow-md":"text-slate-500 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-white/5"}`}><item.icon size={16}/>{item.label}</button>)}</div>
    <div id="profile-panel" role="tabpanel" aria-labelledby={`profile-tab-${tab}`} className="min-h-0 flex-1 overflow-y-auto overscroll-contain p-4 sm:p-6">
     {tab==="essential"?<div className="space-y-4"><section className="rounded-2xl border border-slate-200 bg-slate-50/70 p-4 dark:border-white/10 dark:bg-white/[.035]"><p className="mb-2 text-[10px] font-black uppercase tracking-[.16em] text-primary">{en?"Who am I?":"Qui suis-je ?"}</p><MarkdownContent value={c.shortDescription} className="text-sm font-semibold leading-6 text-slate-600 dark:text-slate-200 [&_p]:my-0 [&_h2]:my-2 [&_h2]:text-lg [&_h3]:my-2 [&_h3]:text-base"/><div className="mt-3 flex flex-wrap gap-2">{c.ageLabel&&<Pill>{c.ageLabel}</Pill>}{c.species&&<Pill>{c.species}</Pill>}</div></section>{c.motto&&<blockquote className="rounded-2xl border-l-4 bg-slate-50 px-4 py-3 text-sm font-bold italic leading-6 text-slate-700 dark:bg-white/5 dark:text-slate-200" style={{borderColor:c.color}}><span className="mb-1 block text-[10px] not-italic uppercase tracking-[.16em] text-slate-400">{en?"Favourite saying":"Sa devise"}</span>“{c.motto}”</blockquote>}</div>:<div className="space-y-3">{c.biography&&<Info icon={<BookOpen size={18}/>} title={en?"Story":"Biographie"} value={c.biography}/>}<div className="grid items-start gap-3 xl:grid-cols-2">{c.personality&&<Info icon={<Sparkles size={18}/>} title={en?"Personality":"Personnalité"} value={c.personality}/>} {c.hobbies&&<Info icon={<Heart size={18}/>} title={en?"Hobbies":"Passions & loisirs"} value={c.hobbies}/>}</div></div>}
    </div>
    <footer className="flex shrink-0 flex-wrap justify-end gap-2 border-t border-slate-200 bg-slate-50/70 p-3 dark:border-white/10 dark:bg-slate-950/25 sm:px-5"><button onClick={close} className="min-h-10 rounded-xl border border-slate-200 px-4 text-sm font-bold transition hover:bg-white dark:border-white/10 dark:text-slate-300 dark:hover:bg-white/5">{en?"Close":"Fermer"}</button><Link href={href} onClick={close} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-black text-white shadow-md transition hover:-translate-y-0.5 hover:brightness-110">{active?(en?"Images filtered":"Filtre appliqué"):(en?"View illustrations":"Voir ses illustrations")}<ArrowRight size={16}/></Link></footer>
   </div>
  </div>
 </div>,document.body)
}
function Info({icon,title,value}:{icon:React.ReactNode;title:string;value:string}){return <section className="min-w-0 rounded-2xl border border-slate-200 bg-slate-50/70 p-4 dark:border-white/10 dark:bg-white/[.035]"><h3 className="flex items-center gap-2 text-sm font-black dark:text-white"><span className="grid size-8 place-items-center rounded-lg bg-primary/10 text-primary">{icon}</span>{title}</h3><MarkdownContent value={value} className="mt-2 break-words text-sm leading-6 text-slate-600 dark:text-slate-300 [&_p]:my-1 [&_h2]:my-2 [&_h2]:text-lg [&_h3]:my-2 [&_h3]:text-base [&_ul]:my-2 [&_ol]:my-2"/></section>}
function Pill({children}:{children:React.ReactNode}){return <span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-black text-slate-600 dark:bg-white/10 dark:text-slate-200">{children}</span>}
