"use client";

import { ArrowDownUp, Check, ChevronDown, RotateCcw, Search, SlidersHorizontal, Tags } from "lucide-react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import type {Locale} from "@/lib/i18n";

type Option={value:string;label:string};

export function ListingFilters({title,query,category,sort="newest",categories=[],searchPlaceholder,showCategoryFilter=false,categoryLabel,allCategoriesLabel,locale="fr"}:{title:string;query?:string;category?:string;sort?:string;categories?:Array<{slug:string;name:string}>;searchPlaceholder?:string;showCategoryFilter?:boolean;categoryLabel?:string;allCategoriesLabel?:string;locale?:Locale}){
 const en=locale==="en",pathname=usePathname(),hasFilters=Boolean(query?.trim()||category||sort!=="newest"),hasCategoryFilter=showCategoryFilter||categories.length>0,resolvedSearchPlaceholder=searchPlaceholder??(en?"Search…":"Rechercher…"),resolvedCategoryLabel=categoryLabel??(en?"Category":"Catégorie"),resolvedAllCategoriesLabel=allCategoriesLabel??(en?"All categories":"Toutes les catégories");
 return <form className="relative z-20 mb-6 rounded-[1.5rem] border bg-card/95 p-3 shadow-[0_14px_45px_-34px_rgba(15,23,42,.45)] backdrop-blur md:p-4"><div className="mb-3 flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><SlidersHorizontal size={17}/></span><div className="min-w-0"><p className="truncate font-display font-black text-foreground">{title}</p><p className="truncate text-[11px] font-semibold text-foreground/50">{en?"Search and sort content in a few clicks":"Recherchez et classez les contenus en quelques clics"}</p></div></div>{hasFilters&&<Link href={pathname} scroll={false} className="inline-flex min-h-9 shrink-0 items-center gap-2 rounded-xl border bg-background px-3 text-xs font-black text-foreground/65 transition hover:border-primary/40 hover:text-primary focus-visible:ring-4 focus-visible:ring-primary/20"><RotateCcw size={14}/> <span className="hidden sm:inline">{en?"Reset":"Réinitialiser"}</span></Link>}</div><div className={`grid gap-2.5 md:grid-cols-2 ${hasCategoryFilter?"xl:grid-cols-[minmax(240px,1.4fr)_minmax(240px,1fr)_minmax(190px,.8fr)_auto]":"xl:grid-cols-[minmax(280px,1fr)_minmax(210px,.55fr)_auto]"}`}><label className="group relative"><span className="sr-only">{en?"Search":"Rechercher"}</span><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-foreground/35 transition group-focus-within:text-primary" size={17}/><input name="q" defaultValue={query} placeholder={resolvedSearchPlaceholder} className="focus-ring min-h-12 w-full rounded-xl border bg-background/70 pl-11 pr-4 font-semibold text-foreground placeholder:text-foreground/40"/></label>{hasCategoryFilter&&<FilterSelect name="category" label={resolvedCategoryLabel} icon={<Tags size={16}/>} value={category||""} options={[{value:"",label:resolvedAllCategoriesLabel},...categories.map(item=>({value:item.slug,label:item.name}))]}/>}<FilterSelect name="sort" label={en?"Sort":"Classement"} icon={<ArrowDownUp size={16}/>} value={sort} options={[{value:"newest",label:en?"Newest":"Plus récents"},{value:"oldest",label:en?"Oldest":"Plus anciens"}]}/><button className="group inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-primary px-3 pl-5 font-black text-white shadow-md shadow-primary/20 transition duration-300 hover:-translate-y-1 hover:scale-[1.02] hover:brightness-110 hover:shadow-lg hover:shadow-primary/30 active:translate-y-0 active:scale-95 focus-visible:ring-4 focus-visible:ring-primary/25 md:col-span-2 xl:col-span-1"><span>{en?"Apply":"Appliquer"}</span><span className="grid size-8 place-items-center rounded-full bg-white/15 transition duration-300 group-hover:rotate-[-8deg] group-hover:scale-110 group-hover:bg-white/25"><Check size={17} strokeWidth={3}/></span></button></div></form>
}

function FilterSelect({name,label,icon,value:initial,options}:{name:string;label:string;icon:React.ReactNode;value:string;options:Option[]}){const[value,setValue]=useState(initial),[open,setOpen]=useState(false),root=useRef<HTMLDivElement>(null),selected=options.find(option=>option.value===value)??options[0];useEffect(()=>{const close=(event:MouseEvent)=>{if(!root.current?.contains(event.target as Node))setOpen(false)},escape=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false)};document.addEventListener("mousedown",close);document.addEventListener("keydown",escape);return()=>{document.removeEventListener("mousedown",close);document.removeEventListener("keydown",escape)}},[]);return <div ref={root} className="relative"><input type="hidden" name={name} value={value}/><button type="button" aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(current=>!current)} className={`flex min-h-12 w-full items-center gap-3 rounded-xl border bg-background/70 px-4 text-left transition ${open?"border-primary ring-4 ring-primary/10":"hover:border-primary/40"}`}><span className="text-primary">{icon}</span><span className="min-w-0 flex-1"><span className="block text-[9px] font-black uppercase tracking-[.14em] text-foreground/45">{label}</span><span className="block truncate text-sm font-bold text-foreground">{selected.label}</span></span><ChevronDown size={16} className={`shrink-0 transition ${open?"rotate-180 text-primary":"text-foreground/45"}`}/></button>{open&&<div role="listbox" className="absolute left-0 right-0 top-[calc(100%+.45rem)] z-50 max-h-[min(24rem,60vh)] overflow-y-auto overscroll-contain rounded-2xl border bg-card p-2 shadow-2xl"><p className="sticky top-0 z-10 bg-card px-3 pb-2 pt-1 text-[10px] font-black uppercase tracking-[.14em] text-foreground/40">{label}</p>{options.map(option=><button key={option.value||"all"} type="button" role="option" aria-selected={option.value===value} onClick={()=>{setValue(option.value);setOpen(false)}} className={`flex min-h-11 w-full items-center justify-between rounded-xl px-3 text-left text-sm font-bold transition ${option.value===value?"bg-primary text-white":"text-foreground hover:bg-primary/10 hover:text-primary"}`}><span>{option.label}</span>{option.value===value&&<Check size={17}/>}</button>)}</div>}</div>}
