import type {Metadata} from "next";
import {ActivityCard} from "@/components/content-cards";
import {ListingFilters} from "@/components/public/listing-filters";
import {EmptyState,Pagination} from "@/components/ui";
import {contentRepository} from "@/repositories/content.repository";
import {hasClubAccess} from "@/lib/club-access";

export const metadata:Metadata={title:"Free printable activities for children",description:"Download free coloring pages, educational games and creative printable activities.",alternates:{canonical:"/en/activities",languages:{fr:"/activites",en:"/en/activities"}}};
export default async function EnglishActivitiesPage({searchParams}:{searchParams:Promise<{page?:string;q?:string;category?:string;type?:string;sort?:string}>}){const s=await searchParams,sort=s.sort==="oldest"?"oldest":"newest",[r,club,categories,activityTypes]=await Promise.all([contentRepository.activities({page:Number(s.page)||1,pageSize:24,search:s.q,category:s.category,activityType:s.type,sort,language:"EN"}),hasClubAccess(),contentRepository.activityCategoryOptions("EN"),contentRepository.activityTypeOptions("EN")]);return <section className="container py-8"><header className="mb-6"><p className="text-xs font-black uppercase tracking-[.2em] text-primary">Pick up your crayons</p><h1 className="mt-2 font-display text-4xl font-black">Free activities to print</h1><p className="mt-2 text-foreground/60">A few minutes of printing, hours of creativity.</p></header><ListingFilters locale="en" title="Find an activity" query={s.q} category={s.category} activityType={s.type} sort={sort} categories={categories} activityTypes={activityTypes} searchPlaceholder="Search activities…"/><p className="mb-4 text-sm font-semibold text-foreground/60">{r.total} activit{r.total===1?"y":"ies"} found</p><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{r.items.length?r.items.map((item,index)=><ActivityCard locale="en" key={item.id} item={item} index={index} clubUnlocked={club}/>):<EmptyState locale="en" title="No English activities yet"/>}</div><Pagination locale="en" page={r.page} pages={r.pages} path="/en/activities" query={{q:s.q,category:s.category,type:s.type,sort}}/></section>}
