import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Play } from "lucide-react";
import { Badge, Card } from "./ui";
import { BookImageCarousel } from "./public/book-image-carousel";
import { ClubDownloadButton } from "./public/club-download-button";
import { ActivityImageCarousel } from "./public/activity-image-carousel";
import { localizedPath, type Locale } from "@/lib/i18n";

const colors = ["bg-[#d9eadf]", "bg-[#f6dfce]", "bg-[#dce4f3]", "bg-[#f1dce4]"];

export function BookCard({ item, category, coverPath, gallery = [], index = 0,locale="fr" }: { item: { title: string; slug: string; shortDescription: string; description: string; ageMin: number | null; ageMax: number | null; pageCount: number | null; amazonUrl: string | null; pricingType: "FREE"|"PAID"; priceCents: number|null; currency: string }; category?: { name: string; color: string; badge: string } | null; coverPath?: string | null; gallery?: Array<{ path: string; alt: string | null }>; index?: number;locale?:Locale }) {
  const en=locale==="en",href = `${localizedPath("books",locale)}/${item.slug}`;
  const external = false;
  const images = [...(coverPath ? [{ path: coverPath, alt: `${en?"Cover of":"Couverture de"} ${item.title}` }] : []), ...gallery.map(image => ({ path: image.path, alt: image.alt || `${en?"Image of":"Image de"} ${item.title}` }))];
  const fallback = <div className="h-[78%] w-[45%] rotate-[-4deg] rounded-md border-4 border-white/80 bg-card p-4 text-center shadow-xl transition duration-300 group-hover:rotate-0 group-hover:scale-105"><span className="text-4xl">{["🦊", "🌿", "🚀", "🐳"][index % 4]}</span><p className="mt-4 font-display text-sm font-black">{item.title}</p></div>;
  return <Card className="group flex h-full flex-col overflow-hidden dark:border-white/10"><div className={`aspect-[4/3] ${colors[index % 4]} relative grid place-items-center overflow-hidden`}><BookImageCarousel images={images} title={item.title} fallback={fallback}/></div><div className="flex flex-1 flex-col p-5 sm:p-6"><div className="grid min-h-[4.75rem] content-start gap-2"><div className="flex min-h-6 min-w-0 items-start">{category&&<span title={category.name} className="inline-flex max-w-full items-center gap-1.5 rounded-full px-3 py-1 text-xs font-black uppercase tracking-wide" style={{backgroundColor:`${category.color}20`,color:category.color}}><span aria-hidden="true" className="shrink-0">{category.badge}</span><span className="truncate">{category.name}</span></span>}</div><div className="flex flex-wrap items-center gap-2"><Badge>{item.ageMin ?? 3}–{item.ageMax ?? 8} {en?"years":"ans"}</Badge>{item.pageCount && <Badge>{item.pageCount} pages</Badge>}<span className={`whitespace-nowrap rounded-full px-3 py-1 text-xs font-black uppercase tracking-wide ${item.pricingType==="FREE"?"bg-emerald-100 text-emerald-800 dark:bg-emerald-500/15 dark:text-emerald-300":"bg-blue-100 text-blue-800 dark:bg-blue-500/15 dark:text-blue-300"}`}>{item.pricingType==="FREE"?(en?"Free":"Gratuit"):item.priceCents?new Intl.NumberFormat(en?"en-GB":"fr-FR",{style:"currency",currency:item.currency}).format(item.priceCents/100):(en?"Paid":"Payant")}</span></div></div><h3 className="mt-4 text-balance font-display text-2xl font-bold">{item.title}</h3><Link className="mt-auto inline-flex items-center gap-2 pt-5 font-bold text-primary" href={href} target={external ? "_blank" : undefined} rel={external ? "noopener noreferrer" : undefined}>{en?"Discover":"Découvrir"} <ArrowRight size={17}/></Link></div></Card>;
}

export function ActivityCard({ item, index = 0, clubUnlocked = false,locale="fr" }: { item: { id: string; title: string; description: string; pageCount: number | null; accessLevel: "PUBLIC" | "CLUB"; downloadEnabled: boolean; previewPath?: string | null; previewAlt?: string | null; gallery?: Array<{path:string;alt:string|null}>; activityType?:{name:string;color:string;badge:string}|null; categories?:Array<{name:string;color:string;badge:string}> }; index?: number; clubUnlocked?: boolean;locale?:Locale }) {
  const en=locale==="en";
  const gallery=item.gallery?.length?item.gallery:item.previewPath?[{path:item.previewPath,alt:item.previewAlt??null}]:[];
  return <Card className="group flex h-full flex-col overflow-hidden dark:border-white/10"><div className={`relative aspect-[4/3] ${colors[(index + 1) % 4]} grid place-items-center overflow-hidden`}>{gallery.length?<ActivityImageCarousel images={gallery} title={item.title} locale={locale}/>:<span className="text-7xl transition group-hover:scale-110">{["✏️", "🧩", "🔎", "🦁"][index % 4]}</span>}</div><div className="flex flex-1 flex-col p-5"><div className="flex flex-wrap gap-2">{item.activityType&&<span className="rounded-full px-3 py-1 text-xs font-black uppercase tracking-wide" style={{backgroundColor:`${item.activityType.color}20`,color:item.activityType.color}}>{item.activityType.badge} {item.activityType.name}</span>}{item.categories?.map(category=><span key={`${category.name}-${category.badge}`} title={category.name} className="inline-flex max-w-full items-center gap-1.5 rounded-full px-3 py-1 text-xs font-black uppercase tracking-wide" style={{backgroundColor:`${category.color}20`,color:category.color}}><span aria-hidden="true">{category.badge}</span><span className="truncate">{category.name}</span></span>)}<Badge>{en?"Free":"Gratuit"} · {item.pageCount ?? 1} pages</Badge>{item.accessLevel === "CLUB" && <Badge>Instagram Club</Badge>}</div><h3 className="mt-3 text-balance font-display text-xl font-bold">{item.title}</h3><div className="mt-auto"><ClubDownloadButton locale={locale} activityId={item.id} clubOnly={item.accessLevel === "CLUB"} unlocked={clubUnlocked} enabled={item.downloadEnabled}/></div></div></Card>;
}

export function PostCard({ item, coverPath,locale="fr" }: { item: { title: string; slug: string; excerpt: string }; coverPath?: string | null;locale?:Locale }) {
  const en=locale==="en";
  return <Card className="group flex h-full flex-col overflow-hidden dark:border-white/10">
    {coverPath && <div className="relative aspect-[16/9] overflow-hidden bg-secondary/30"><Image src={`/media/${coverPath}`} alt={`${en?"Illustration for":"Illustration de"} ${item.title}`} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover transition duration-500 group-hover:scale-[1.03]"/></div>}
    <div className="flex flex-1 flex-col p-6"><Badge>Inspiration</Badge><h3 className="mt-4 text-balance font-display text-2xl font-bold leading-tight">{item.title}</h3><p className="mt-3 line-clamp-3 leading-relaxed text-foreground/60">{item.excerpt}</p><Link className="mt-auto inline-flex items-center gap-2 pt-6 font-bold text-primary" href={`${localizedPath("blog",locale)}/${item.slug}`}>{en?"Read article":"Lire l’article"} <ArrowRight size={17}/></Link></div>
  </Card>;
}

export function VlogCard({ item, thumbnailPath,locale="fr" }: { item: { title: string; description: string }; thumbnailPath?: string | null;locale?:Locale }) {
  const en=locale==="en";
  return <Card className="group flex h-full flex-col overflow-hidden dark:border-white/10"><div className="relative grid aspect-video place-items-center overflow-hidden bg-[#dce4f3] dark:bg-slate-900">{thumbnailPath?<Image src={`/media/${thumbnailPath}`} alt={`${en?"Preview of":"Aperçu de"} ${item.title}`} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover transition duration-500 group-hover:scale-[1.03]"/>:<span className="text-6xl">🎨</span>}<span className="absolute grid size-14 place-items-center rounded-full bg-white/95 text-primary shadow-lg transition group-hover:scale-110"><Play fill="currentColor"/></span></div><div className="flex flex-1 flex-col p-5"><h3 className="text-balance font-display text-xl font-bold">{item.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-relaxed text-foreground/60">{item.description}</p><Link href={localizedPath("videos",locale)} className="mt-auto pt-5 font-bold text-primary">{en?"Watch":"Regarder"}</Link></div></Card>;
}
