"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, KeyRound } from "lucide-react";

export function RecoveryForm() {
  const [email, setEmail] = useState(""), [code, setCode] = useState(""), [password, setPassword] = useState(""), [confirmation, setConfirmation] = useState("");
  const [error, setError] = useState(""), [success, setSuccess] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); if (password !== confirmation) return setError("Les mots de passe ne correspondent pas."); const response = await fetch("/api/auth/recover", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, code, newPassword: password }) }); const result = await response.json().catch(() => null) as { message?: string } | null; if (!response.ok) return setError(result?.message || "Réinitialisation impossible."); setSuccess(result?.message || "Mot de passe réinitialisé."); }
  return <main className="grid min-h-screen place-items-center bg-[#f3f6f3] p-5 dark:bg-background"><section className="w-full max-w-lg rounded-[2rem] border bg-white p-7 shadow-2xl dark:border-white/10 dark:bg-card dark:shadow-black/40 sm:p-10"><Link href="/connexion" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-slate-950 dark:text-slate-300 dark:hover:text-white"><ArrowLeft size={17}/> Retour à la connexion</Link><span className="mt-8 grid size-12 place-items-center rounded-2xl bg-emerald-50 text-emerald-700"><KeyRound/></span><h1 className="mt-5 text-3xl font-black">Récupérer l’accès</h1><p className="mt-2 text-slate-500 dark:text-slate-300">Utilisez l’un des codes enregistrés depuis la page Sécurité.</p>{error && <p className="mt-5 rounded-xl bg-red-50 p-4 font-bold text-red-700">{error}</p>}{success ? <div className="mt-6 rounded-2xl bg-emerald-50 p-6 text-center"><CheckCircle2 className="mx-auto text-emerald-700" size={45}/><p className="mt-3 font-bold text-emerald-800">{success}</p><Link href="/connexion" className="mt-5 inline-block rounded-xl bg-slate-950 px-6 py-3 font-bold text-white">Se connecter</Link></div> : <form onSubmit={submit} className="mt-7 space-y-4">{[["Adresse e-mail", "email", email, setEmail], ["Code de récupération", "text", code, setCode], ["Nouveau mot de passe", "password", password, setPassword], ["Confirmer le mot de passe", "password", confirmation, setConfirmation]].map(([label,type,value,setter]) => <label key={label as string} className="block text-sm font-bold">{label as string}<input required type={type as string} value={value as string} onChange={event => (setter as (value:string)=>void)(event.target.value)} className="mt-2 min-h-12 w-full rounded-xl border px-4 outline-none focus:border-emerald-600 focus:ring-4 focus:ring-emerald-50"/></label>)}<p className="text-xs text-slate-500 dark:text-slate-300">Le nouveau mot de passe doit contenir 12 caractères, une majuscule, une minuscule, un chiffre et un caractère spécial.</p><button className="w-full rounded-xl bg-slate-950 py-3 font-black text-white">Réinitialiser le mot de passe</button></form>}</section></main>;
}
