import {eq,inArray} from "drizzle-orm";
import {z} from "zod";
import {auth} from "@/auth";
import {db} from "@/db";
import {characters,coloringGameCharacters,coloringGames,media} from "@/db/schema";
import {storageService} from "@/lib/storage/local-storage";
const patchSchema=z.object({title:z.string().trim().min(3).max(100),description:z.string().trim().min(10).max(400),difficulty:z.enum(["EASY","MEDIUM","HARD"]),ageMin:z.number().int().min(2).max(18).nullable(),ageMax:z.number().int().min(2).max(18).nullable(),published:z.boolean(),sortOrder:z.number().int().min(0).max(9999),characterIds:z.array(z.string().uuid()).max(12)});
async function admin(){return(await auth())?.user.role==="ADMIN"}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){if(!await admin())return Response.json({message:"Non autorisé."},{status:401});const{id}=await params,parsed=patchSchema.safeParse(await request.json());if(!parsed.success)return Response.json({message:"Vérifiez le formulaire."},{status:400});if(parsed.data.ageMin!==null&&parsed.data.ageMax!==null&&parsed.data.ageMax<parsed.data.ageMin)return Response.json({message:"La tranche d’âge est invalide."},{status:400});const valid=parsed.data.characterIds.length?await db.select({id:characters.id}).from(characters).where(inArray(characters.id,parsed.data.characterIds)):[];if(valid.length!==parsed.data.characterIds.length)return Response.json({message:"Un personnage est invalide."},{status:400});const{characterIds,...data}=parsed.data;await db.transaction(async tx=>{await tx.update(coloringGames).set({...data,updatedAt:new Date()}).where(eq(coloringGames.id,id));await tx.delete(coloringGameCharacters).where(eq(coloringGameCharacters.coloringGameId,id));if(characterIds.length)await tx.insert(coloringGameCharacters).values(characterIds.map(characterId=>({coloringGameId:id,characterId}))) });return Response.json({message:"Coloriage mis à jour."})}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){if(!await admin())return Response.json({message:"Non autorisé."},{status:401});const{id}=await params,[game]=await db.select({sourceMediaId:coloringGames.sourceMediaId,path:media.path}).from(coloringGames).leftJoin(media,eq(coloringGames.sourceMediaId,media.id)).where(eq(coloringGames.id,id));await db.transaction(async tx=>{await tx.delete(coloringGames).where(eq(coloringGames.id,id));if(game?.sourceMediaId)await tx.delete(media).where(eq(media.id,game.sourceMediaId))});if(game?.path)await storageService.deleteFile(game.path).catch(()=>undefined);return Response.json({message:"Coloriage supprimé."})}
