import type {Metadata} from "next";
import {Images,Sparkles} from "lucide-react";
import {mediaRepository} from "@/repositories/media.repository";
import {GalleryEmpty,ImageGallery} from "@/components/public/image-gallery";
import {Pagination} from "@/components/ui";
import {ListingFilters} from "@/components/public/listing-filters";
import {CharacterFilter} from "@/components/public/character-filter";
import {hasClubAccess} from "@/lib/club-access";
export const metadata:Metadata={title:"Creative illustration gallery",description:"Explore original creations from Le Petit Crayon.",alternates:{canonical:"/en/images",languages:{fr:"/images",en:"/en/images"}}};
export default async function EnglishImagesPage({searchParams}:{searchParams:Promise<{page?:string;q?:string;category?:string;character?:string;sort?:string}>}){
 const params=await searchParams,sort=params.sort==="oldest"?"oldest":"newest",clubAccess=await hasClubAccess();
 const[result,categories,characters]=await Promise.all([mediaRepository.paginatedImages({page:Number(params.page)||1,pageSize:12,search:params.q,category:params.category,character:params.character,sort,includeClub:clubAccess,language:"EN"}),mediaRepository.imageCategoryOptions("EN"),mediaRepository.characterOptions("EN")]),filtered=Boolean(params.q?.trim()||params.category||params.character);
 return <section className="min-h-[calc(100vh-4rem)] bg-gradient-to-b from-[#f7f4ed] to-background py-6 dark:from-[#111a18] dark:to-background md:py-8"><div className="container"><header className="mb-5 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><span className="inline-flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-primary"><Sparkles size={14}/>Creative gallery</span><h1 className="mt-2 font-display text-3xl font-black dark:text-white md:text-4xl">A world to discover <span className="text-primary">through images.</span></h1><p className="mt-1.5 text-sm text-foreground/65 md:text-base">Original creations to explore, love and revisit together.</p></div><div className="inline-flex w-fit items-center gap-2 rounded-2xl border bg-card/85 px-3 py-2"><Images className="text-primary" size={18}/><strong>{result.total}</strong><span className="text-xs text-foreground/55">image{result.total===1?"":"s"}</span></div></header><ListingFilters locale="en" title="Find an illustration" query={params.q} category={params.category} sort={sort} categories={categories} searchPlaceholder="Title, character, category…"/><CharacterFilter locale="en" options={characters} selected={params.character} path="/en/images" query={{q:params.q,category:params.category,sort}}/><p className="mb-4 text-sm font-semibold text-foreground/60">{result.total} image{result.total===1?"":"s"} found</p>{result.items.length?<ImageGallery items={result.items}/>:<GalleryEmpty locale="en" filtered={filtered} resetHref="/en/images"/>}<Pagination locale="en" page={result.page} pages={result.pages} path="/en/images" query={{q:params.q,category:params.category,character:params.character,sort}}/></div></section>;
}
