import sharp from "sharp";
import {asc,eq,inArray} from "drizzle-orm";
import {z} from "zod";
import {auth} from "@/auth";
import {db} from "@/db";
import {characters,media,mediaCharacters} from "@/db/schema";
import {slugify} from "@/lib/utils";
import {storageService} from "@/lib/storage/local-storage";

export const runtime="nodejs";
const schema=z.object({language:z.enum(["FR","EN"]),name:z.string().trim().min(2).max(80),shortDescription:z.string().trim().min(10).max(240),biography:z.string().trim().max(3000),ageLabel:z.string().trim().max(50),species:z.string().trim().max(80),personality:z.string().trim().max(500),hobbies:z.string().trim().max(500),motto:z.string().trim().max(180),color:z.string().regex(/^#[0-9A-F]{6}$/i),published:z.boolean(),sortOrder:z.number().int().min(0).max(9999)});
async function admin(){return(await auth())?.user.role==="ADMIN"}
export async function GET(){if(!await admin())return Response.json({message:"Non autorisé."},{status:401});const items=await db.select({character:characters,portrait:media}).from(characters).leftJoin(media,eq(characters.portraitMediaId,media.id)).orderBy(asc(characters.language),asc(characters.sortOrder),asc(characters.name));const links=items.length?await db.select().from(mediaCharacters).where(inArray(mediaCharacters.characterId,items.map(row=>row.character.id))):[];return Response.json({items:items.map(row=>({...row,imageCount:links.filter(link=>link.characterId===row.character.id).length}))})}
export async function POST(request:Request){if(!await admin())return Response.json({message:"Non autorisé."},{status:401});const form=await request.formData(),parsed=schema.safeParse({language:form.get("language"),name:form.get("name"),shortDescription:form.get("shortDescription"),biography:form.get("biography")||"",ageLabel:form.get("ageLabel")||"",species:form.get("species")||"",personality:form.get("personality")||"",hobbies:form.get("hobbies")||"",motto:form.get("motto")||"",color:form.get("color")||"#0F8A68",published:form.get("published")==="true",sortOrder:Number(form.get("sortOrder")||0)});if(!parsed.success)return Response.json({message:"Vérifiez les informations du personnage."},{status:400});try{const id=crypto.randomUUID(),portrait=form.get("portrait");let portraitMediaId:string|null=null;if(portrait instanceof File&&portrait.size){await storageService.validateFile(portrait,"IMAGE");const meta=await sharp(Buffer.from(await portrait.arrayBuffer())).metadata(),stored=await storageService.uploadFile(portrait,"IMAGE");portraitMediaId=crypto.randomUUID();await db.insert(media).values({id:portraitMediaId,type:"IMAGE",filename:stored.filename,originalName:portrait.name,mimeType:stored.mimeType,size:stored.size,width:meta.width,height:meta.height,path:stored.path,alt:`Portrait de ${parsed.data.name}`,language:parsed.data.language,galleryEnabled:false,published:false,accessLevel:"PUBLIC"})}await db.insert(characters).values({id,...parsed.data,slug:`${slugify(parsed.data.name)}-${id.slice(0,6)}`,portraitMediaId,biography:parsed.data.biography||null,ageLabel:parsed.data.ageLabel||null,species:parsed.data.species||null,personality:parsed.data.personality||null,hobbies:parsed.data.hobbies||null,motto:parsed.data.motto||null});return Response.json({message:"Personnage créé avec succès.",id},{status:201})}catch(error){return Response.json({message:error instanceof Error?error.message:"Création impossible."},{status:400})}}
